#ifndef RGTK4_AUTOGEN_CALLBACKS_H
#define RGTK4_AUTOGEN_CALLBACKS_H

#include <gtk/gtk.h>
#ifdef HAVE_GTKSOURCE
#include <gtksourceview/gtksource.h>
#endif
#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

extern void _rgtk4_cb_CacheDestroyFunc(gpointer value);
extern gpointer _rgtk4_cb_CacheDupFunc(gpointer value);
extern gpointer _rgtk4_cb_CacheNewFunc(gpointer key);
extern void _rgtk4_cb_ChildWatchFunc(GPid pid, gint wait_status, gpointer user_data);
extern void _rgtk4_cb_ClearHandleFunc(guint handle_id);
extern gint _rgtk4_cb_CompareDataFunc(gconstpointer a, gconstpointer b, gpointer user_data);
extern gint _rgtk4_cb_CompareFunc(gconstpointer a, gconstpointer b);
extern gchar* _rgtk4_cb_CompletionFunc(gpointer item);
extern gint _rgtk4_cb_CompletionStrncmpFunc(const gchar* s1, const gchar* s2, gsize n);
extern gpointer _rgtk4_cb_CopyFunc(gconstpointer src, gpointer data);
extern void _rgtk4_cb_DataForeachFunc(GQuark key_id, gpointer data, gpointer user_data);
extern void _rgtk4_cb_DestroyNotify(gpointer data);
extern gpointer _rgtk4_cb_DuplicateFunc(gpointer data, gpointer user_data);
extern gboolean _rgtk4_cb_EqualFunc(gconstpointer a, gconstpointer b);
extern gboolean _rgtk4_cb_EqualFuncFull(gconstpointer a, gconstpointer b, gpointer user_data);
extern void _rgtk4_cb_ErrorClearFunc(GError* error);
extern void _rgtk4_cb_ErrorCopyFunc(const GError* src_error, GError* dest_error);
extern void _rgtk4_cb_ErrorInitFunc(GError* error);
extern void _rgtk4_cb_FreeFunc(gpointer data);
extern void _rgtk4_cb_Func(gpointer data, gpointer user_data);
extern void _rgtk4_cb_HFunc(gpointer key, gpointer value, gpointer user_data);
extern gboolean _rgtk4_cb_HRFunc(gpointer key, gpointer value, gpointer user_data);
extern guint _rgtk4_cb_HashFunc(gconstpointer key);
extern gboolean _rgtk4_cb_HookCheckFunc(gpointer data);
extern gboolean _rgtk4_cb_HookCheckMarshaller(GHook* hook, gpointer marshal_data);
extern gint _rgtk4_cb_HookCompareFunc(GHook* new_hook, GHook* sibling);
extern void _rgtk4_cb_HookFinalizeFunc(GHookList* hook_list, GHook* hook);
extern gboolean _rgtk4_cb_HookFindFunc(GHook* hook, gpointer data);
extern void _rgtk4_cb_HookFunc(gpointer data);
extern void _rgtk4_cb_HookMarshaller(GHook* hook, gpointer marshal_data);
extern gboolean _rgtk4_cb_IOFunc(GIOChannel* source, GIOCondition condition, gpointer data);
extern GSource* _rgtk4_cb_io_create_watch(GIOChannel* channel, GIOCondition condition);
extern void _rgtk4_cb_io_free(GIOChannel* channel);
extern GIOFlags _rgtk4_cb_io_get_flags(GIOChannel* channel);
extern void _rgtk4_cb_LogFunc(const gchar* log_domain, GLogLevelFlags log_level, const gchar* message, gpointer user_data);
extern GLogWriterOutput _rgtk4_cb_LogWriterFunc(GLogLevelFlags log_level, const GLogField* fields, gsize n_fields, gpointer user_data);
extern void _rgtk4_cb_error(GtkBuildableParseContext* context, GError* error, gpointer user_data);
extern gpointer _rgtk4_cb_malloc(gsize n_bytes);
extern gpointer _rgtk4_cb_realloc(gpointer mem, gsize n_bytes);
extern void _rgtk4_cb_free(gpointer mem);
extern gpointer _rgtk4_cb_calloc(gsize n_blocks, gsize n_block_bytes);
extern gpointer _rgtk4_cb_try_malloc(gsize n_bytes);
extern gpointer _rgtk4_cb_try_realloc(gpointer mem, gsize n_bytes);
extern void _rgtk4_cb_NodeForeachFunc(GNode* node, gpointer data);
extern gboolean _rgtk4_cb_NodeTraverseFunc(GNode* node, gpointer data);
extern gint _rgtk4_cb_PollFunc(GPollFD* ufds, guint nfsd, gint timeout_);
extern void _rgtk4_cb_PrintFunc(const gchar* string);
extern gboolean _rgtk4_cb_RegexEvalCallback(const GMatchInfo* match_info, GString* result, gpointer user_data);
extern void _rgtk4_cb_ScannerMsgFunc(GScanner* scanner, gchar* message, gboolean error);
extern gint _rgtk4_cb_SequenceIterCompareFunc(GSequenceIter* a, GSequenceIter* b, gpointer data);
extern void _rgtk4_cb_ref(gpointer cb_data);
extern void _rgtk4_cb_unref(gpointer cb_data);
extern void _rgtk4_cb_SourceDisposeFunc(GSource* source);
extern void _rgtk4_cb_SourceDummyMarshal(void);
extern gboolean _rgtk4_cb_SourceFunc(gpointer user_data);
extern gboolean _rgtk4_cb_SourceFuncsCheckFunc(GSource* source);
extern void _rgtk4_cb_SourceFuncsFinalizeFunc(GSource* source);
extern gboolean _rgtk4_cb_SourceFuncsPrepareFunc(GSource* source, gint* timeout_);
extern void _rgtk4_cb_SourceOnceFunc(gpointer user_data);
extern void _rgtk4_cb_SpawnChildSetupFunc(gpointer data);
extern void _rgtk4_cb_TestDataFunc(gconstpointer user_data);
extern void _rgtk4_cb_TestFixtureFunc(gpointer fixture, gconstpointer user_data);
extern void _rgtk4_cb_TestFunc(void);
extern gboolean _rgtk4_cb_TestLogFatalFunc(const gchar* log_domain, GLogLevelFlags log_level, const gchar* message, gpointer user_data);
extern gpointer _rgtk4_cb_ThreadFunc(gpointer data);
extern GMutex* _rgtk4_cb_mutex_new(void);
extern void _rgtk4_cb_mutex_lock(GMutex* mutex);
extern gboolean _rgtk4_cb_mutex_trylock(GMutex* mutex);
extern void _rgtk4_cb_mutex_unlock(GMutex* mutex);
extern void _rgtk4_cb_mutex_free(GMutex* mutex);
extern GCond* _rgtk4_cb_cond_new(void);
extern void _rgtk4_cb_cond_signal(GCond* cond);
extern void _rgtk4_cb_cond_broadcast(GCond* cond);
extern void _rgtk4_cb_cond_wait(GCond* cond, GMutex* mutex);
extern gboolean _rgtk4_cb_cond_timed_wait(GCond* cond, GMutex* mutex, GTimeVal* end_time);
extern void _rgtk4_cb_cond_free(GCond* cond);
extern GPrivate* _rgtk4_cb_private_new(GDestroyNotify destructor);
extern gpointer _rgtk4_cb_private_get(GPrivate* private_key);
extern void _rgtk4_cb_private_set(GPrivate* private_key, gpointer data);
extern void _rgtk4_cb_thread_yield(void);
extern void _rgtk4_cb_thread_join(gpointer thread);
extern void _rgtk4_cb_thread_exit(void);
extern void _rgtk4_cb_thread_self(gpointer thread);
extern gboolean _rgtk4_cb_thread_equal(gpointer thread1, gpointer thread2);
extern const gchar* _rgtk4_cb_TranslateFunc(const gchar* str, gpointer data);
extern gboolean _rgtk4_cb_TraverseFunc(gpointer key, gpointer value, gpointer data);
extern gboolean _rgtk4_cb_TraverseNodeFunc(GTreeNode* node, gpointer data);
extern void _rgtk4_cb_VoidFunc(void);
extern void _rgtk4_cb_BaseFinalizeFunc(gpointer g_class);
extern void _rgtk4_cb_BaseInitFunc(gpointer g_class);
extern gboolean _rgtk4_cb_BindingTransformFunc(GBinding* binding, const GValue* from_value, GValue* to_value, gpointer user_data);
extern gpointer _rgtk4_cb_BoxedCopyFunc(gpointer boxed);
extern void _rgtk4_cb_BoxedFreeFunc(gpointer boxed);
extern void _rgtk4_cb_Callback(void);
extern void _rgtk4_cb_ClassFinalizeFunc(gpointer g_class, gpointer class_data);
extern void _rgtk4_cb_ClassInitFunc(gpointer g_class, gpointer class_data);
extern void _rgtk4_cb_marshal(GClosure* closure, GValue* return_value, guint n_param_values, const GValue* param_values, gpointer invocation_hint, gpointer marshal_data);
extern void _rgtk4_cb_ClosureMarshal(GClosure* closure, GValue* return_value, guint n_param_values, const GValue* param_values, gpointer invocation_hint, gpointer marshal_data);
extern void _rgtk4_cb_ClosureNotify(gpointer data, GClosure* closure);
extern void _rgtk4_cb_set_property(GObject* object, guint property_id, const GValue* value, GParamSpec* pspec);
extern void _rgtk4_cb_get_property(GObject* object, guint property_id, GValue* value, GParamSpec* pspec);
extern void _rgtk4_cb_dispose(GObject* object);
extern void _rgtk4_cb_finalize(GParamSpec* pspec);
extern void _rgtk4_cb_dispatch_properties_changed(GObject* object, guint n_pspecs, GParamSpec** pspecs);
extern void _rgtk4_cb_notify(GObject* object, GParamSpec* pspec);
extern void _rgtk4_cb_constructed(GObject* object);
extern void _rgtk4_cb_InstanceInitFunc(GTypeInstance* instance, gpointer g_class);
extern void _rgtk4_cb_InterfaceFinalizeFunc(gpointer g_iface, gpointer iface_data);
extern void _rgtk4_cb_InterfaceInitFunc(gpointer g_iface, gpointer iface_data);
extern void _rgtk4_cb_ObjectFinalizeFunc(GObject* object);
extern void _rgtk4_cb_ObjectGetPropertyFunc(GObject* object, guint property_id, GValue* value, GParamSpec* pspec);
extern void _rgtk4_cb_ObjectSetPropertyFunc(GObject* object, guint property_id, const GValue* value, GParamSpec* pspec);
extern void _rgtk4_cb_value_set_default(GParamSpec* pspec, GValue* value);
extern gboolean _rgtk4_cb_value_validate(GParamSpec* pspec, GValue* value);
extern gint _rgtk4_cb_values_cmp(GParamSpec* pspec, const GValue* value1, const GValue* value2);
extern gboolean _rgtk4_cb_value_is_valid(GParamSpec* pspec, const GValue* value);
extern void _rgtk4_cb_instance_init(GParamSpec* pspec);
extern gboolean _rgtk4_cb_SignalAccumulator(GSignalInvocationHint* ihint, GValue* return_accu, const GValue* handler_return, gpointer data);
extern gboolean _rgtk4_cb_SignalEmissionHook(GSignalInvocationHint* ihint, guint n_param_values, const GValue* param_values, gpointer data);
extern void _rgtk4_cb_ToggleNotify(gpointer data, GObject* object, gboolean is_last_ref);
extern gboolean _rgtk4_cb_TypeClassCacheFunc(gpointer cache_data, GTypeClass* g_class);
extern void _rgtk4_cb_TypeInterfaceCheckFunc(gpointer check_data, gpointer g_iface);
extern void _rgtk4_cb_unload(GTypeModule* module);
extern void _rgtk4_cb_reserved1(void);
extern void _rgtk4_cb_reserved2(void);
extern void _rgtk4_cb_reserved3(void);
extern void _rgtk4_cb_reserved4(void);
extern void _rgtk4_cb_TypePluginCompleteInterfaceInfo(GTypePlugin* plugin, GType instance_type, GType interface_type, GInterfaceInfo* info);
extern void _rgtk4_cb_TypePluginCompleteTypeInfo(GTypePlugin* plugin, GType g_type, GTypeInfo* info, GTypeValueTable* value_table);
extern void _rgtk4_cb_TypePluginUnuse(GTypePlugin* plugin);
extern void _rgtk4_cb_TypePluginUse(GTypePlugin* plugin);
extern gchar* _rgtk4_cb_TypeValueCollectFunc(GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags);
extern void _rgtk4_cb_TypeValueCopyFunc(const GValue* src_value, GValue* dest_value);
extern void _rgtk4_cb_TypeValueFreeFunc(GValue* value);
extern void _rgtk4_cb_TypeValueInitFunc(GValue* value);
extern gchar* _rgtk4_cb_TypeValueLCopyFunc(const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags);
extern gpointer _rgtk4_cb_TypeValuePeekPointerFunc(const GValue* value);
extern void _rgtk4_cb_ValueTransform(const GValue* src_value, GValue* dest_value);
extern void _rgtk4_cb_WeakNotify(gpointer data, GObject* where_the_object_was);
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_activate(GtkSourceGutterRenderer* renderer, GtkTextIter* iter, GdkRectangle* area, guint button, GdkModifierType state, gint n_presses);
#endif
extern void _rgtk4_cb_change_state(GAction* action, GVariant* value);
extern gboolean _rgtk4_cb_has_action(GActionGroup* action_group, const gchar* action_name);
extern gchar** _rgtk4_cb_list_actions(GActionGroup* action_group);
extern gboolean _rgtk4_cb_get_action_enabled(GActionGroup* action_group, const gchar* action_name);
extern const GVariantType* _rgtk4_cb_get_action_parameter_type(GActionGroup* action_group, const gchar* action_name);
extern const GVariantType* _rgtk4_cb_get_action_state_type(GActionGroup* action_group, const gchar* action_name);
extern GVariant* _rgtk4_cb_get_action_state_hint(GActionGroup* action_group, const gchar* action_name);
extern GVariant* _rgtk4_cb_get_action_state(GActionGroup* action_group, const gchar* action_name);
extern void _rgtk4_cb_change_action_state(GActionGroup* action_group, const gchar* action_name, GVariant* value);
extern void _rgtk4_cb_activate_action(GActionGroup* action_group, const gchar* action_name, GVariant* parameter);
extern void _rgtk4_cb_action_added(GActionGroup* action_group, const gchar* action_name);
extern void _rgtk4_cb_action_removed(GActionGroup* action_group, const gchar* action_name);
extern void _rgtk4_cb_action_enabled_changed(GActionGroup* action_group, const gchar* action_name, gboolean enabled);
extern void _rgtk4_cb_action_state_changed(GActionGroup* action_group, const gchar* action_name, GVariant* state);
extern gboolean _rgtk4_cb_query_action(GActionGroup* action_group, const gchar* action_name, gboolean* enabled, const GVariantType** parameter_type, const GVariantType** state_type, GVariant** state_hint, GVariant** state);
extern const char* _rgtk4_cb_get_name(PangoFontFamily* family);
extern const GVariantType* _rgtk4_cb_get_parameter_type(GAction* action);
extern const GVariantType* _rgtk4_cb_get_state_type(GAction* action);
extern GVariant* _rgtk4_cb_get_state_hint(GAction* action);
extern gboolean _rgtk4_cb_get_enabled(GAction* action);
extern GVariant* _rgtk4_cb_get_state(GAction* action);
extern GAction* _rgtk4_cb_lookup_action(GActionMap* action_map, const gchar* action_name);
extern void _rgtk4_cb_add_action(GActionMap* action_map, GAction* action);
extern void _rgtk4_cb_remove_action(GActionMap* action_map, const gchar* action_name);
extern GFile* _rgtk4_cb_dup(GFile* file);
extern gboolean _rgtk4_cb_equal(const PangoAttribute* attr1, const PangoAttribute* attr2);
extern const char* _rgtk4_cb_get_id(GtkBuildable* buildable);
extern const char* _rgtk4_cb_get_description(GAppInfo* appinfo);
extern const char* _rgtk4_cb_get_executable(GAppInfo* appinfo);
extern GIcon* _rgtk4_cb_get_icon(GVolume* volume);
extern gboolean _rgtk4_cb_supports_uris(GAppInfo* appinfo);
extern gboolean _rgtk4_cb_supports_files(GAppInfo* appinfo);
extern gboolean _rgtk4_cb_should_show(GAppInfo* appinfo);
extern gboolean _rgtk4_cb_can_remove_supports_type(GAppInfo* appinfo);
extern gboolean _rgtk4_cb_can_delete(GAppInfo* appinfo);
extern gboolean _rgtk4_cb_do_delete(GAppInfo* appinfo);
extern const char* _rgtk4_cb_get_commandline(GAppInfo* appinfo);
extern const char* _rgtk4_cb_get_display_name(GAppInfo* appinfo);
extern const char** _rgtk4_cb_get_supported_types(GAppInfo* appinfo);
extern void _rgtk4_cb_launch_uris_async(GAppInfo* appinfo, GList* uris, GAppLaunchContext* context, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern char* _rgtk4_cb_get_display(GAppLaunchContext* context, GAppInfo* info, GList* files);
extern char* _rgtk4_cb_get_startup_notify_id(GAppLaunchContext* context, GAppInfo* info, GList* files);
extern void _rgtk4_cb_launch_failed(GAppLaunchContext* context, const char* startup_notify_id);
extern void _rgtk4_cb_launched(GAppLaunchContext* context, GAppInfo* info, GVariant* platform_data);
extern void _rgtk4_cb_launch_started(GAppLaunchContext* context, GAppInfo* info, GVariant* platform_data);
extern void _rgtk4_cb__g_reserved1(void);
extern void _rgtk4_cb__g_reserved2(void);
extern void _rgtk4_cb__g_reserved3(void);
extern void _rgtk4_cb_startup(GApplication* application);
extern void _rgtk4_cb_open(GtkMediaFile* self);
extern int _rgtk4_cb_command_line(GApplication* application, GApplicationCommandLine* command_line);
extern gboolean _rgtk4_cb_local_command_line(GApplication* application, gchar*** arguments, int* exit_status);
extern void _rgtk4_cb_before_emit(GApplication* application, GVariant* platform_data);
extern void _rgtk4_cb_after_emit(GApplication* application, GVariant* platform_data);
extern void _rgtk4_cb_add_platform_data(GApplication* application, GVariantBuilder* builder);
extern void _rgtk4_cb_quit_mainloop(GApplication* application);
extern void _rgtk4_cb_run_mainloop(GApplication* application);
extern gint _rgtk4_cb_handle_local_options(GApplication* application, GVariantDict* options);
extern gboolean _rgtk4_cb_name_lost(GApplication* application);
extern void _rgtk4_cb_print_literal(GApplicationCommandLine* cmdline, const gchar* message);
extern void _rgtk4_cb_printerr_literal(GApplicationCommandLine* cmdline, const gchar* message);
extern GInputStream* _rgtk4_cb_get_stdin(GApplicationCommandLine* cmdline);
extern void _rgtk4_cb_init_async(GAsyncInitable* initable, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_AsyncReadyCallback(GObject* source_object, GAsyncResult* res, gpointer data);
extern gpointer _rgtk4_cb_get_user_data(GAsyncResult* res);
extern GObject* _rgtk4_cb_get_source_object(GAsyncResult* res);
extern gboolean _rgtk4_cb_is_tagged(GAsyncResult* res, gpointer source_tag);
extern void _rgtk4_cb_fill_async(GBufferedInputStream* stream, gssize count, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb__g_reserved4(void);
extern void _rgtk4_cb__g_reserved5(void);
extern void _rgtk4_cb_cancelled(GCancellable* cancellable);
extern gboolean _rgtk4_cb_CancellableSourceFunc(GCancellable* cancellable, gpointer data);
extern void _rgtk4_cb_reset(GtkIMContext* context);
extern GDBusObject* _rgtk4_cb_get_object(GDBusObjectManager* manager, const gchar* object_path);
extern void _rgtk4_cb_set_object(GDBusInterface* interface_, GDBusObject* object);
extern GDBusObject* _rgtk4_cb_dup_object(GDBusInterface* interface_);
extern GDBusInterfaceVTable* _rgtk4_cb_get_vtable(GDBusInterfaceSkeleton* interface_);
extern GVariant* _rgtk4_cb_get_properties(GDBusInterfaceSkeleton* interface_);
extern const gchar* _rgtk4_cb_get_object_path(GDBusObjectManager* manager);
extern GList* _rgtk4_cb_get_interfaces(GDBusObject* object);
extern GDBusInterface* _rgtk4_cb_get_interface(GDBusObjectManager* manager, const gchar* object_path, const gchar* interface_name);
extern void _rgtk4_cb_interface_added(GDBusObjectManager* manager, GDBusObject* object, GDBusInterface* interface_);
extern void _rgtk4_cb_interface_removed(GDBusObjectManager* manager, GDBusObject* object, GDBusInterface* interface_);
extern GList* _rgtk4_cb_get_objects(GDBusObjectManager* manager);
extern void _rgtk4_cb_object_added(GDBusObjectManager* manager, GDBusObject* object);
extern void _rgtk4_cb_object_removed(GDBusObjectManager* manager, GDBusObject* object);
extern void _rgtk4_cb_g_properties_changed(GDBusProxy* proxy, GVariant* changed_properties, const gchar* const* invalidated_properties);
extern void _rgtk4_cb_g_signal(GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
extern GType _rgtk4_cb_DBusProxyTypeFunc(GDBusObjectManagerClient* manager, const gchar* object_path, const gchar* interface_name, gpointer data);
extern GSource* _rgtk4_cb_create_source(GPollableOutputStream* stream, GCancellable* cancellable);
extern GIOCondition _rgtk4_cb_condition_check(GDatagramBased* datagram_based, GIOCondition condition);
extern gboolean _rgtk4_cb_DatagramBasedSourceFunc(GDatagramBased* datagram_based, GIOCondition condition, gpointer data);
extern void _rgtk4_cb_changed(PangoFontMap* fontmap);
extern void _rgtk4_cb_disconnected(GDrive* drive);
extern void _rgtk4_cb_eject_button(GDrive* drive);
extern gboolean _rgtk4_cb_has_volumes(GDrive* drive);
extern GList* _rgtk4_cb_get_volumes(GVolumeMonitor* volume_monitor);
extern gboolean _rgtk4_cb_is_media_removable(GDrive* drive);
extern gboolean _rgtk4_cb_has_media(GDrive* drive);
extern gboolean _rgtk4_cb_is_media_check_automatic(GDrive* drive);
extern gboolean _rgtk4_cb_can_eject(GVolume* volume);
extern gboolean _rgtk4_cb_can_poll_for_media(GDrive* drive);
extern void _rgtk4_cb_eject(GVolume* volume, GMountUnmountFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_poll_for_media(GDrive* drive, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern char* _rgtk4_cb_get_identifier(GVolume* volume, const char* kind);
extern char** _rgtk4_cb_enumerate_identifiers(GVolume* volume);
extern GDriveStartStopType _rgtk4_cb_get_start_stop_type(GDrive* drive);
extern gboolean _rgtk4_cb_can_start(GDrive* drive);
extern gboolean _rgtk4_cb_can_start_degraded(GDrive* drive);
extern void _rgtk4_cb_start(GDrive* drive, GDriveStartFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern gboolean _rgtk4_cb_can_stop(GDrive* drive);
extern void _rgtk4_cb_stop(GDrive* drive, GMountUnmountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_stop_button(GDrive* drive);
extern void _rgtk4_cb_eject_with_operation(GVolume* volume, GMountUnmountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern const gchar* _rgtk4_cb_get_sort_key(GVolume* volume);
extern GIcon* _rgtk4_cb_get_symbolic_icon(GVolume* volume);
extern gboolean _rgtk4_cb_is_removable(GDrive* drive);
extern void _rgtk4_cb_next_files_async(GFileEnumerator* enumerator, int num_files, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_close_async(GOutputStream* stream, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb__g_reserved6(void);
extern void _rgtk4_cb__g_reserved7(void);
extern goffset _rgtk4_cb_tell(GSeekable* seekable);
extern gboolean _rgtk4_cb_can_seek(GSeekable* seekable);
extern void _rgtk4_cb_seek(GtkMediaStream* self, gint64 timestamp);
extern gboolean _rgtk4_cb_can_truncate(GSeekable* seekable);
extern void _rgtk4_cb_query_info_async(GFileOutputStream* stream, const char* attributes, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern char* _rgtk4_cb_get_etag(GFileOutputStream* stream);
extern guint _rgtk4_cb_hash(GIcon* icon);
extern gboolean _rgtk4_cb_is_native(GFile* file);
extern gboolean _rgtk4_cb_has_uri_scheme(GFile* file, const char* uri_scheme);
extern char* _rgtk4_cb_get_uri_scheme(GFile* file);
extern char* _rgtk4_cb_get_basename(GFile* file);
extern GtkTreePath* _rgtk4_cb_get_path(GtkTreeModel* tree_model, GtkTreeIter* iter);
extern char* _rgtk4_cb_get_uri(GFile* file);
extern char* _rgtk4_cb_get_parse_name(GFile* file);
extern GFile* _rgtk4_cb_get_parent(GFile* file);
extern gboolean _rgtk4_cb_prefix_matches(GFile* prefix, GFile* file);
extern char* _rgtk4_cb_get_relative_path(GFile* parent, GFile* descendant);
extern GFile* _rgtk4_cb_resolve_relative_path(GFile* file, const char* relative_path);
extern void _rgtk4_cb_enumerate_children_async(GFile* file, const char* attributes, GFileQueryInfoFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_query_filesystem_info_async(GFile* file, const char* attributes, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_find_enclosing_mount_async(GFile* file, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_set_display_name_async(GFile* file, const char* display_name, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb__query_settable_attributes_async(void);
extern void _rgtk4_cb__query_settable_attributes_finish(void);
extern void _rgtk4_cb__query_writable_namespaces_async(void);
extern void _rgtk4_cb__query_writable_namespaces_finish(void);
extern void _rgtk4_cb_set_attributes_async(GFile* file, GFileInfo* info, GFileQueryInfoFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_read_async(GInputStream* stream, void* buffer, gsize count, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_append_to_async(GFile* file, GFileCreateFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_create_async(GFile* file, GFileCreateFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_replace_async(GFile* file, const char* etag, gboolean make_backup, GFileCreateFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_delete_file_async(GFile* file, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_trash_async(GFile* file, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_make_directory_async(GFile* file, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_make_symbolic_link_async(GFile* file, const char* symlink_value, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern PangoAttribute* _rgtk4_cb_copy(const PangoAttribute* attr);
extern void _rgtk4_cb_copy_async(GFile* source, GFile* destination, GFileCopyFlags flags, int io_priority, GCancellable* cancellable, GFileProgressCallback progress_callback, gpointer progress_callback_data, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_move_async(GFile* source, GFile* destination, GFileCopyFlags flags, int io_priority, GCancellable* cancellable, GFileProgressCallback progress_callback, gpointer progress_callback_data, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_mount_mountable(GFile* file, GMountMountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_unmount_mountable(GFile* file, GMountUnmountFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_eject_mountable(GFile* file, GMountUnmountFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_mount_enclosing_volume(GFile* location, GMountMountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_open_readwrite_async(GFile* file, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_create_readwrite_async(GFile* file, GFileCreateFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_replace_readwrite_async(GFile* file, const char* etag, gboolean make_backup, GFileCreateFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_start_mountable(GFile* file, GDriveStartFlags flags, GMountOperation* start_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_stop_mountable(GFile* file, GMountUnmountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_unmount_mountable_with_operation(GFile* file, GMountUnmountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_eject_mountable_with_operation(GFile* file, GMountUnmountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_poll_mountable(GFile* file, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern gboolean _rgtk4_cb_query_exists(GFile* file, GCancellable* cancellable);
extern void _rgtk4_cb_FileMeasureProgressCallback(gboolean reporting, guint64 current_size, guint64 num_dirs, guint64 num_files, gpointer data);
extern gboolean _rgtk4_cb_cancel(GFileMonitor* monitor);
extern void _rgtk4_cb_FileProgressCallback(goffset current_num_bytes, goffset total_num_bytes, gpointer data);
extern gboolean _rgtk4_cb_FileReadMoreCallback(const char* file_contents, goffset file_size, gpointer callback_data);
extern void _rgtk4_cb_got_completion_data(GFilenameCompleter* filename_completer);
extern gboolean _rgtk4_cb_IOSchedulerJobFunc(GIOSchedulerJob* job, GCancellable* cancellable, gpointer data);
extern GInputStream* _rgtk4_cb_get_input_stream(GIOStream* stream);
extern GOutputStream* _rgtk4_cb_get_output_stream(GIOStream* stream);
extern void _rgtk4_cb__g_reserved8(void);
extern void _rgtk4_cb__g_reserved9(void);
extern void _rgtk4_cb__g_reserved10(void);
extern gboolean _rgtk4_cb_to_tokens(GIcon* icon, GPtrArray* tokens, gint* out_version);
extern void _rgtk4_cb_serialize(GSocketControlMessage* message, gpointer data);
extern gchar* _rgtk4_cb_to_string(GSocketConnectable* connectable);
extern const guint8* _rgtk4_cb_to_bytes(GInetAddress* address);
extern void _rgtk4_cb_skip_async(GInputStream* stream, gsize count, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern GType _rgtk4_cb_get_item_type(GListModel* list);
extern gint _rgtk4_cb_get_n_items(GMenuModel* model);
extern gpointer _rgtk4_cb_get_item(GListModel* list, guint position);
extern void _rgtk4_cb_load_async(GLoadableIcon* icon, int size, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_low_memory_warning(GMemoryMonitor* monitor, GMemoryMonitorWarningLevel level);
extern gboolean _rgtk4_cb_get_next(GMenuLinkIter* iter, const gchar** out_link, GMenuModel** value);
extern gboolean _rgtk4_cb_is_mutable(GMenuModel* model);
extern void _rgtk4_cb_get_item_attributes(GMenuModel* model, gint item_index, GHashTable** attributes);
extern GMenuAttributeIter* _rgtk4_cb_iterate_item_attributes(GMenuModel* model, gint item_index);
extern GVariant* _rgtk4_cb_get_item_attribute_value(GMenuModel* model, gint item_index, const gchar* attribute, const GVariantType* expected_type);
extern void _rgtk4_cb_get_item_links(GMenuModel* model, gint item_index, GHashTable** links);
extern GMenuLinkIter* _rgtk4_cb_iterate_item_links(GMenuModel* model, gint item_index);
extern GMenuModel* _rgtk4_cb_get_item_link(GMenuModel* model, gint item_index, const gchar* link);
extern void _rgtk4_cb_unmounted(GMount* mount);
extern GFile* _rgtk4_cb_get_root(GMount* mount);
extern char* _rgtk4_cb_get_uuid(GVolume* volume);
extern GVolume* _rgtk4_cb_get_volume(GMount* mount);
extern GDrive* _rgtk4_cb_get_drive(GVolume* volume);
extern gboolean _rgtk4_cb_can_unmount(GMount* mount);
extern void _rgtk4_cb_unmount(GMount* mount, GMountUnmountFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_remount(GMount* mount, GMountMountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_guess_content_type(GMount* mount, gboolean force_rescan, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_pre_unmount(GMount* mount);
extern void _rgtk4_cb_unmount_with_operation(GMount* mount, GMountUnmountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern GFile* _rgtk4_cb_get_default_location(GMount* mount);
extern void _rgtk4_cb_ask_question(GMountOperation* op, const char* message, const char** choices);
extern void _rgtk4_cb_reply(GMountOperation* op, GMountOperationResult result);
extern void _rgtk4_cb_aborted(GMountOperation* op);
extern void _rgtk4_cb_show_processes(GMountOperation* op, const gchar* message, GArray* processes, const gchar** choices);
extern void _rgtk4_cb_show_unmount_progress(GMountOperation* op, const gchar* message, gint64 time_left, gint64 bytes_left);
extern void _rgtk4_cb_network_changed(GNetworkMonitor* monitor, gboolean network_available);
extern void _rgtk4_cb_can_reach_async(GNetworkMonitor* monitor, GSocketConnectable* connectable, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_write_async(GOutputStream* stream, void* buffer, gsize count, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_splice_async(GOutputStream* stream, GInputStream* source, GOutputStreamSpliceFlags flags, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_flush_async(GOutputStream* stream, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_writev_async(GOutputStream* stream, const GOutputVector* vectors, gsize n_vectors, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_acquire_async(GPermission* permission, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_release_async(GPermission* permission, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern gboolean _rgtk4_cb_can_poll(GPollableOutputStream* stream);
extern gboolean _rgtk4_cb_is_readable(GPollableInputStream* stream);
extern gboolean _rgtk4_cb_is_writable(GPollableOutputStream* stream);
extern gboolean _rgtk4_cb_PollableSourceFunc(GObject* pollable_stream, gpointer data);
extern void _rgtk4_cb_connect_async(GProxy* proxy, GIOStream* connection, GProxyAddress* proxy_address, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern gboolean _rgtk4_cb_supports_hostname(GProxy* proxy);
extern gboolean _rgtk4_cb_is_supported(void);
extern void _rgtk4_cb_lookup_async(GProxyResolver* resolver, const gchar* uri, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern gpointer _rgtk4_cb_ReallocFunc(gpointer data, gsize size);
extern void _rgtk4_cb_activate_action_full(GRemoteActionGroup* remote, const gchar* action_name, GVariant* parameter, GVariant* platform_data);
extern void _rgtk4_cb_change_action_state_full(GRemoteActionGroup* remote, const gchar* action_name, GVariant* value, GVariant* platform_data);
extern void _rgtk4_cb_reload(GResolver* resolver);
extern void _rgtk4_cb_lookup_by_name_async(GResolver* resolver, const gchar* hostname, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_lookup_by_address_async(GResolver* resolver, GInetAddress* address, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_lookup_service_async(GResolver* resolver, const gchar* rrname, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_lookup_records_async(GResolver* resolver, const gchar* rrname, GResolverRecordType record_type, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_lookup_by_name_with_flags_async(GResolver* resolver, const gchar* hostname, GResolverNameLookupFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern GVariant* _rgtk4_cb_read(GSettingsBackend* backend, const gchar* key, const GVariantType* expected_type, gboolean default_value);
extern gboolean _rgtk4_cb_get_writable(GSettingsBackend* backend, const gchar* key);
extern gboolean _rgtk4_cb_write(GSettingsBackend* backend, const gchar* key, GVariant* value, gpointer origin_tag);
extern gboolean _rgtk4_cb_write_tree(GSettingsBackend* backend, GTree* tree, gpointer origin_tag);
extern void _rgtk4_cb_subscribe(GSettingsBackend* backend, const gchar* name);
extern void _rgtk4_cb_unsubscribe(GSettingsBackend* backend, const gchar* name);
extern void _rgtk4_cb_sync(GSettingsBackend* backend);
extern GVariant* _rgtk4_cb_read_user_value(GSettingsBackend* backend, const gchar* key, const GVariantType* expected_type);
extern gboolean _rgtk4_cb_SettingsBindGetMapping(GValue* value, GVariant* variant, gpointer user_data);
extern GVariant* _rgtk4_cb_SettingsBindSetMapping(const GValue* value, const GVariantType* expected_type, gpointer user_data);
extern void _rgtk4_cb_writable_changed(GSettings* settings, const gchar* key);
extern gboolean _rgtk4_cb_writable_change_event(GSettings* settings, GQuark key);
extern gboolean _rgtk4_cb_change_event(GSettings* settings, const GQuark* keys, gint n_keys);
extern gboolean _rgtk4_cb_SettingsGetMapping(GVariant* value, gpointer* result, gpointer user_data);
extern void _rgtk4_cb_SimpleAsyncThreadFunc(GSimpleAsyncResult* res, GObject* object, GCancellable* cancellable);
extern PangoFontFamily* _rgtk4_cb_get_family(PangoFontMap* fontmap, const char* name);
extern gssize _rgtk4_cb_get_native_size(GSocketAddress* address);
extern void _rgtk4_cb_next_async(GSocketAddressEnumerator* enumerator, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern int _rgtk4_cb_event(GtkCellArea* area, GtkCellAreaContext* context, GtkWidget* widget, GdkEvent* event, const GdkRectangle* cell_area, GtkCellRendererState flags);
extern GSocketAddressEnumerator* _rgtk4_cb_enumerate(GSocketConnectable* connectable);
extern GSocketAddressEnumerator* _rgtk4_cb_proxy_enumerate(GSocketConnectable* connectable);
extern void _rgtk4_cb_get_size(GdkPixbufAnimation* animation, int* width, int* height);
extern int _rgtk4_cb_get_level(GSocketControlMessage* message);
extern int _rgtk4_cb_get_type(GSocketControlMessage* message);
extern gboolean _rgtk4_cb_incoming(GSocketService* service, GSocketConnection* connection, GObject* source_object);
extern gboolean _rgtk4_cb_SocketSourceFunc(GSocket* socket, GIOCondition condition, gpointer data);
extern void _rgtk4_cb_TaskThreadFunc(GTask* task, gpointer source_object, gpointer task_data, GCancellable* cancellable);
extern gboolean _rgtk4_cb_run(GThreadedSocketService* service, GSocketConnection* connection, GObject* source_object);
extern gboolean _rgtk4_cb_supports_tls(GTlsBackend* backend);
extern GType _rgtk4_cb_get_certificate_type(void);
extern GType _rgtk4_cb_get_client_connection_type(void);
extern GType _rgtk4_cb_get_server_connection_type(void);
extern GType _rgtk4_cb_get_file_database_type(void);
extern GTlsDatabase* _rgtk4_cb_get_default_database(GTlsBackend* backend);
extern gboolean _rgtk4_cb_supports_dtls(GTlsBackend* backend);
extern GType _rgtk4_cb_get_dtls_client_connection_type(void);
extern GType _rgtk4_cb_get_dtls_server_connection_type(void);
extern GTlsCertificateFlags _rgtk4_cb_verify(GTlsCertificate* cert, GSocketConnectable* identity, GTlsCertificate* trusted_ca);
extern void _rgtk4_cb_copy_session_state(GTlsClientConnection* conn, GTlsClientConnection* source);
extern void _rgtk4_cb_verify_chain_async(GTlsDatabase* self, GTlsCertificate* chain, const gchar* purpose, GSocketConnectable* identity, GTlsInteraction* interaction, GTlsDatabaseVerifyFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern gchar* _rgtk4_cb_create_certificate_handle(GTlsDatabase* self, GTlsCertificate* certificate);
extern void _rgtk4_cb_lookup_certificate_for_handle_async(GTlsDatabase* self, const gchar* handle, GTlsInteraction* interaction, GTlsDatabaseLookupFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_lookup_certificate_issuer_async(GTlsDatabase* self, GTlsCertificate* certificate, GTlsInteraction* interaction, GTlsDatabaseLookupFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_lookup_certificates_issued_by_async(GTlsDatabase* self, GByteArray* issuer_raw_dn, GTlsInteraction* interaction, GTlsDatabaseLookupFlags flags, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_ask_password_async(GTlsInteraction* interaction, GTlsPassword* password, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_get_value(GtkTreeModel* tree_model, GtkTreeIter* iter, int column, GValue* value);
extern void _rgtk4_cb_set_value(GTlsPassword* password, guchar* value, gssize length, GDestroyNotify destroy);
extern const gchar* _rgtk4_cb_get_default_warning(GTlsPassword* password);
extern gboolean _rgtk4_cb_is_active(GVfs* vfs);
extern GFile* _rgtk4_cb_get_file_for_path(GVfs* vfs, const char* path);
extern GFile* _rgtk4_cb_get_file_for_uri(GVfs* vfs, const char* uri);
extern const gchar* const* _rgtk4_cb_get_supported_uri_schemes(GVfs* vfs);
extern GFile* _rgtk4_cb_parse_name(GVfs* vfs, const char* parse_name);
extern void _rgtk4_cb_local_file_add_info(GVfs* vfs, const char* filename, guint64 device, GFileAttributeMatcher* attribute_matcher, GFileInfo* info, GCancellable* cancellable, gpointer* extra_data, GDestroyNotify* free_extra_data);
extern void _rgtk4_cb_add_writable_namespaces(GVfs* vfs, GFileAttributeInfoList* list);
extern void _rgtk4_cb_local_file_removed(GVfs* vfs, const char* filename);
extern void _rgtk4_cb_local_file_moved(GVfs* vfs, const char* source, const char* dest);
extern GFile* _rgtk4_cb_VfsFileLookupFunc(GVfs* vfs, const char* identifier, gpointer user_data);
extern void _rgtk4_cb_removed(GVolume* volume);
extern GMount* _rgtk4_cb_get_mount(GVolume* volume);
extern gboolean _rgtk4_cb_can_mount(GVolume* volume);
extern void _rgtk4_cb_mount_fn(GVolume* volume, GMountMountFlags flags, GMountOperation* mount_operation, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern gboolean _rgtk4_cb_should_automount(GVolume* volume);
extern GFile* _rgtk4_cb_get_activation_root(GVolume* volume);
extern void _rgtk4_cb_volume_added(GVolumeMonitor* volume_monitor, GVolume* volume);
extern void _rgtk4_cb_volume_removed(GVolumeMonitor* volume_monitor, GVolume* volume);
extern void _rgtk4_cb_volume_changed(GVolumeMonitor* volume_monitor, GVolume* volume);
extern void _rgtk4_cb_mount_added(GVolumeMonitor* volume_monitor, GMount* mount);
extern void _rgtk4_cb_mount_removed(GVolumeMonitor* volume_monitor, GMount* mount);
extern void _rgtk4_cb_mount_pre_unmount(GVolumeMonitor* volume_monitor, GMount* mount);
extern void _rgtk4_cb_mount_changed(GVolumeMonitor* volume_monitor, GMount* mount);
extern void _rgtk4_cb_drive_connected(GVolumeMonitor* volume_monitor, GDrive* drive);
extern void _rgtk4_cb_drive_disconnected(GVolumeMonitor* volume_monitor, GDrive* drive);
extern void _rgtk4_cb_drive_changed(GVolumeMonitor* volume_monitor, GDrive* drive);
extern GList* _rgtk4_cb_get_connected_drives(GVolumeMonitor* volume_monitor);
extern GList* _rgtk4_cb_get_mounts(GVolumeMonitor* volume_monitor);
extern GVolume* _rgtk4_cb_get_volume_for_uuid(GVolumeMonitor* volume_monitor, const char* uuid);
extern GMount* _rgtk4_cb_get_mount_for_uuid(GVolumeMonitor* volume_monitor, const char* uuid);
extern void _rgtk4_cb_drive_eject_button(GVolumeMonitor* volume_monitor, GDrive* drive);
extern void _rgtk4_cb_drive_stop_button(GVolumeMonitor* volume_monitor, GDrive* drive);
extern void _rgtk4_cb_ContentDeserializeFunc(GdkContentDeserializer* deserializer);
extern void _rgtk4_cb_content_changed(GdkContentProvider* provider);
extern void _rgtk4_cb_attach_clipboard(GdkContentProvider* provider, GdkClipboard* clipboard);
extern void _rgtk4_cb_detach_clipboard(GdkContentProvider* provider, GdkClipboard* clipboard);
extern GdkContentFormats* _rgtk4_cb_ref_formats(GdkContentProvider* provider);
extern GdkContentFormats* _rgtk4_cb_ref_storable_formats(GdkContentProvider* provider);
extern void _rgtk4_cb_write_mime_type_async(GdkContentProvider* provider, const char* mime_type, GOutputStream* stream, int io_priority, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
extern void _rgtk4_cb_ContentSerializeFunc(GdkContentSerializer* serializer);
extern GdkTexture* _rgtk4_cb_CursorGetTextureCallback(GdkCursor* cursor, int cursor_size, double scale, int* width, int* height, int* hotspot_x, int* hotspot_y, gpointer data);
extern void _rgtk4_cb_snapshot(GtkWidget* widget, GtkSnapshot* snapshot);
extern GdkPaintable* _rgtk4_cb_get_current_image(GdkPaintable* paintable);
extern GtkTreeModelFlags _rgtk4_cb_get_flags(GtkTreeModel* tree_model);
extern int _rgtk4_cb_get_intrinsic_width(GdkPaintable* paintable);
extern int _rgtk4_cb_get_intrinsic_height(GdkPaintable* paintable);
extern double _rgtk4_cb_get_intrinsic_aspect_ratio(GdkPaintable* paintable);
extern GtkATContext* _rgtk4_cb_get_at_context(GtkAccessible* self);
extern gboolean _rgtk4_cb_get_platform_state(GtkAccessible* self, GtkAccessiblePlatformState state);
extern GtkAccessible* _rgtk4_cb_get_accessible_parent(GtkAccessible* self);
extern GtkAccessible* _rgtk4_cb_get_first_accessible_child(GtkAccessible* self);
extern GtkAccessible* _rgtk4_cb_get_next_accessible_sibling(GtkAccessible* self);
extern gboolean _rgtk4_cb_get_bounds(GtkAccessible* self, int* x, int* y, int* width, int* height);
extern char* _rgtk4_cb_get_accessible_id(GtkAccessible* self);
extern gboolean _rgtk4_cb_set_current_value(GtkAccessibleRange* self, double value);
extern GBytes* _rgtk4_cb_get_contents(GtkAccessibleText* self, unsigned int start, unsigned int end);
extern GBytes* _rgtk4_cb_get_contents_at(GtkAccessibleText* self, unsigned int offset, GtkAccessibleTextGranularity granularity, unsigned int* start, unsigned int* end);
extern unsigned int _rgtk4_cb_get_caret_position(GtkAccessibleText* self);
extern gboolean _rgtk4_cb_get_selection(GtkAccessibleText* self, gsize* n_ranges, GtkAccessibleTextRange** ranges);
extern gboolean _rgtk4_cb_get_attributes(GtkAccessibleText* self, unsigned int offset, gsize* n_ranges, GtkAccessibleTextRange** ranges, char*** attribute_names, char*** attribute_values);
extern void _rgtk4_cb_get_default_attributes(GtkAccessibleText* self, char*** attribute_names, char*** attribute_values);
extern gboolean _rgtk4_cb_get_extents(GtkAccessibleText* self, unsigned int start, unsigned int end, graphene_rect_t* extents);
extern gboolean _rgtk4_cb_get_offset(GtkAccessibleText* self, const graphene_point_t* point, unsigned int* offset);
extern gboolean _rgtk4_cb_set_caret_position(GtkAccessibleText* self, unsigned int offset);
extern gboolean _rgtk4_cb_set_selection(GtkSelectionModel* model, GtkBitset* selected, GtkBitset* mask);
extern const char* _rgtk4_cb_get_action_name(GtkActionable* actionable);
extern void _rgtk4_cb_set_action_name(GtkActionable* actionable, const char* action_name);
extern GVariant* _rgtk4_cb_get_action_target_value(GtkActionable* actionable);
extern void _rgtk4_cb_set_action_target_value(GtkActionable* actionable, GVariant* target_value);
extern void _rgtk4_cb_value_changed(GtkScaleButton* button, double value);
extern void _rgtk4_cb__gtk_reserved1(void);
extern void _rgtk4_cb__gtk_reserved2(void);
extern void _rgtk4_cb__gtk_reserved3(void);
extern void _rgtk4_cb__gtk_reserved4(void);
extern void _rgtk4_cb_window_added(GtkApplication* application, GtkWindow* window);
extern void _rgtk4_cb_window_removed(GtkApplication* application, GtkWindow* window);
extern int _rgtk4_cb_AssistantPageFunc(int current_page, gpointer data);
extern void _rgtk4_cb_set_id(GtkBuildable* buildable, const char* id);
extern void _rgtk4_cb_add_child(GtkBuildable* buildable, GtkBuilder* builder, GObject* child, const char* type);
extern void _rgtk4_cb_set_buildable_property(GtkBuildable* buildable, GtkBuilder* builder, const char* name, const GValue* value);
extern gboolean _rgtk4_cb_custom_tag_start(GtkBuildable* buildable, GtkBuilder* builder, GObject* child, const char* tagname, GtkBuildableParser* parser, gpointer* data);
extern void _rgtk4_cb_custom_tag_end(GtkBuildable* buildable, GtkBuilder* builder, GObject* child, const char* tagname, gpointer data);
extern void _rgtk4_cb_custom_finished(GtkBuildable* buildable, GtkBuilder* builder, GObject* child, const char* tagname, gpointer data);
extern void _rgtk4_cb_parser_finished(GtkBuildable* buildable, GtkBuilder* builder);
extern GObject* _rgtk4_cb_get_internal_child(GtkBuildable* buildable, GtkBuilder* builder, const char* childname);
extern GType _rgtk4_cb_get_type_from_name(GtkBuilderScope* self, GtkBuilder* builder, const char* type_name);
extern GType _rgtk4_cb_get_type_from_function(GtkBuilderScope* self, GtkBuilder* builder, const char* function_name);
extern void _rgtk4_cb_clicked(GtkButton* button);
extern gboolean _rgtk4_cb_CellAllocCallback(GtkCellRenderer* renderer, const GdkRectangle* cell_area, const GdkRectangle* cell_background, gpointer data);
extern void _rgtk4_cb_add(GtkCellArea* area, GtkCellRenderer* renderer);
extern void _rgtk4_cb_remove(GtkCellArea* area, GtkCellRenderer* renderer);
extern void _rgtk4_cb_foreach(PangoFontset* fontset, PangoFontsetForeachFunc func, gpointer data);
extern void _rgtk4_cb_foreach_alloc(GtkCellArea* area, GtkCellAreaContext* context, GtkWidget* widget, const GdkRectangle* cell_area, const GdkRectangle* background_area, GtkCellAllocCallback callback, gpointer callback_data);
extern void _rgtk4_cb_apply_attributes(GtkCellArea* area, GtkTreeModel* tree_model, GtkTreeIter* iter, gboolean is_expander, gboolean is_expanded);
extern GtkCellAreaContext* _rgtk4_cb_create_context(GtkCellArea* area);
extern GtkCellAreaContext* _rgtk4_cb_copy_context(GtkCellArea* area, GtkCellAreaContext* context);
extern GtkSizeRequestMode _rgtk4_cb_get_request_mode(GtkWidget* widget);
extern void _rgtk4_cb_get_preferred_width(GtkCellRenderer* cell, GtkWidget* widget, int* minimum_size, int* natural_size);
extern void _rgtk4_cb_get_preferred_height_for_width(GtkCellRenderer* cell, GtkWidget* widget, int width, int* minimum_height, int* natural_height);
extern void _rgtk4_cb_get_preferred_height(GtkCellRenderer* cell, GtkWidget* widget, int* minimum_size, int* natural_size);
extern void _rgtk4_cb_get_preferred_width_for_height(GtkCellRenderer* cell, GtkWidget* widget, int height, int* minimum_width, int* natural_width);
extern void _rgtk4_cb_set_cell_property(GtkCellArea* area, GtkCellRenderer* renderer, guint property_id, const GValue* value, GParamSpec* pspec);
extern void _rgtk4_cb_get_cell_property(GtkCellArea* area, GtkCellRenderer* renderer, guint property_id, GValue* value, GParamSpec* pspec);
extern gboolean _rgtk4_cb_focus(GtkWidget* widget, GtkDirectionType direction);
extern gboolean _rgtk4_cb_is_activatable(GtkCellArea* area);
extern void _rgtk4_cb_allocate(GtkLayoutManager* manager, GtkWidget* widget, int width, int height, int baseline);
extern gboolean _rgtk4_cb_CellCallback(GtkCellRenderer* renderer, gpointer data);
extern void _rgtk4_cb_editing_done(GtkCellEditable* cell_editable);
extern void _rgtk4_cb_remove_widget(GtkCellEditable* cell_editable);
extern GtkCellEditable* _rgtk4_cb_start_editing(GtkCellRenderer* cell, GdkEvent* event, GtkWidget* widget, const char* path, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags);
extern void _rgtk4_cb_CellLayoutDataFunc(GtkCellLayout* cell_layout, GtkCellRenderer* cell, GtkTreeModel* tree_model, GtkTreeIter* iter, gpointer data);
extern void _rgtk4_cb_pack_start(GtkCellLayout* cell_layout, GtkCellRenderer* cell, gboolean expand);
extern void _rgtk4_cb_pack_end(GtkCellLayout* cell_layout, GtkCellRenderer* cell, gboolean expand);
extern void _rgtk4_cb_clear(GtkCellLayout* cell_layout);
extern void _rgtk4_cb_add_attribute(GtkCellLayout* cell_layout, GtkCellRenderer* cell, const char* attribute, int column);
extern void _rgtk4_cb_set_cell_data_func(GtkCellLayout* cell_layout, GtkCellRenderer* cell, GtkCellLayoutDataFunc func, gpointer func_data, GDestroyNotify destroy);
extern void _rgtk4_cb_clear_attributes(GtkCellLayout* cell_layout, GtkCellRenderer* cell);
extern void _rgtk4_cb_reorder(GtkCellLayout* cell_layout, GtkCellRenderer* cell, int position);
extern GList* _rgtk4_cb_get_cells(GtkCellLayout* cell_layout);
extern GtkCellArea* _rgtk4_cb_get_area(GtkCellLayout* cell_layout);
extern void _rgtk4_cb_get_aligned_area(GtkCellRenderer* cell, GtkWidget* widget, GtkCellRendererState flags, const GdkRectangle* cell_area, GdkRectangle* aligned_area);
extern void _rgtk4_cb_editing_canceled(GtkCellRenderer* cell);
extern void _rgtk4_cb_editing_started(GtkCellRenderer* cell, GtkCellEditable* editable, const char* path);
extern void _rgtk4_cb_edited(GtkCellRendererText* cell_renderer_text, const char* path, const char* new_text);
extern void _rgtk4_cb_toggled(GtkToggleButton* toggle_button);
extern void _rgtk4_cb_get_rgba(GtkColorChooser* chooser, GdkRGBA* color);
extern void _rgtk4_cb_set_rgba(GtkColorChooser* chooser, const GdkRGBA* color);
extern void _rgtk4_cb_add_palette(GtkColorChooser* chooser, GtkOrientation orientation, int colors_per_line, int n_colors, GdkRGBA* colors);
extern void _rgtk4_cb_color_activated(GtkColorChooser* chooser, const GdkRGBA* color);
extern char* _rgtk4_cb_format_entry_text(GtkComboBox* combo_box, const char* path);
extern void _rgtk4_cb_CustomAllocateFunc(GtkWidget* widget, int width, int height, int baseline);
extern gboolean _rgtk4_cb_CustomFilterFunc(gpointer item, gpointer user_data);
extern void _rgtk4_cb_CustomMeasureFunc(GtkWidget* widget, GtkOrientation orientation, int for_size, int* minimum, int* natural, int* minimum_baseline, int* natural_baseline);
extern GtkSizeRequestMode _rgtk4_cb_CustomRequestModeFunc(GtkWidget* widget);
extern void _rgtk4_cb_response(GtkNativeDialog* self, int response_id);
extern void _rgtk4_cb_close(GtkMediaFile* self);
extern void _rgtk4_cb_resize(GtkGLArea* area, int width, int height);
extern void _rgtk4_cb_DrawingAreaDrawFunc(GtkDrawingArea* drawing_area, cairo_t* cr, int width, int height, gpointer user_data);
extern void _rgtk4_cb_insert_text(GtkTextBuffer* buffer, GtkTextIter* pos, const char* new_text, int new_text_length);
extern guint _rgtk4_cb_delete_text(GtkEntryBuffer* buffer, guint position, guint n_chars);
extern const char* _rgtk4_cb_get_text(GtkEntryBuffer* buffer, gsize* n_bytes);
extern void _rgtk4_cb_do_insert_text(GtkEditable* editable, const char* text, int length, int* position);
extern void _rgtk4_cb_do_delete_text(GtkEditable* editable, int start_pos, int end_pos);
extern gboolean _rgtk4_cb_get_selection_bounds(GtkEditable* editable, int* start_pos, int* end_pos);
extern void _rgtk4_cb_set_selection_bounds(GtkEditable* editable, int start_pos, int end_pos);
extern GtkEditable* _rgtk4_cb_get_delegate(GtkEditable* editable);
extern void _rgtk4_cb_inserted_text(GtkEntryBuffer* buffer, guint position, const char* chars, guint n_chars);
extern void _rgtk4_cb_deleted_text(GtkEntryBuffer* buffer, guint position, guint n_chars);
extern guint _rgtk4_cb_get_length(GtkEntryBuffer* buffer);
extern void _rgtk4_cb__gtk_reserved5(void);
extern void _rgtk4_cb__gtk_reserved6(void);
extern void _rgtk4_cb__gtk_reserved7(void);
extern void _rgtk4_cb__gtk_reserved8(void);
extern gboolean _rgtk4_cb_EntryCompletionMatchFunc(GtkEntryCompletion* completion, const char* key, GtkTreeIter* iter, gpointer user_data);
extern void _rgtk4_cb_ExpressionNotify(gpointer user_data);
extern gboolean _rgtk4_cb_match(GtkFilter* self, gpointer item);
extern GtkFilterMatch _rgtk4_cb_get_strictness(GtkFilter* self);
extern GtkWidget* _rgtk4_cb_FlowBoxCreateWidgetFunc(gpointer item, gpointer user_data);
extern gboolean _rgtk4_cb_FlowBoxFilterFunc(GtkFlowBoxChild* child, gpointer user_data);
extern void _rgtk4_cb_FlowBoxForeachFunc(GtkFlowBox* box, GtkFlowBoxChild* child, gpointer user_data);
extern int _rgtk4_cb_FlowBoxSortFunc(GtkFlowBoxChild* child1, GtkFlowBoxChild* child2, gpointer user_data);
extern PangoFontFamily* _rgtk4_cb_get_font_family(GtkFontChooser* fontchooser);
extern PangoFontFace* _rgtk4_cb_get_font_face(GtkFontChooser* fontchooser);
extern int _rgtk4_cb_get_font_size(GtkFontChooser* fontchooser);
extern void _rgtk4_cb_set_filter_func(GtkFontChooser* fontchooser, GtkFontFilterFunc filter, gpointer user_data, GDestroyNotify destroy);
extern void _rgtk4_cb_font_activated(GtkFontChooser* chooser, const char* fontname);
extern void _rgtk4_cb_set_font_map(GtkFontChooser* fontchooser, PangoFontMap* fontmap);
extern PangoFontMap* _rgtk4_cb_get_font_map(PangoFont* font);
extern gboolean _rgtk4_cb_FontFilterFunc(const PangoFontFamily* family, const PangoFontFace* face, gpointer data);
extern void _rgtk4_cb_compute_child_allocation(GtkFrame* frame, GtkAllocation* allocation);
extern gboolean _rgtk4_cb_render(GtkGLArea* area, GdkGLContext* context);
extern void _rgtk4_cb_preedit_start(GtkIMContext* context);
extern void _rgtk4_cb_preedit_end(GtkIMContext* context);
extern void _rgtk4_cb_preedit_changed(GtkIMContext* context);
extern void _rgtk4_cb_commit(GtkIMContext* context, const char* str);
extern gboolean _rgtk4_cb_retrieve_surrounding(GtkIMContext* context);
extern gboolean _rgtk4_cb_delete_surrounding(GtkIMContext* context, int offset, int n_chars);
extern void _rgtk4_cb_set_client_widget(GtkIMContext* context, GtkWidget* widget);
extern void _rgtk4_cb_get_preedit_string(GtkIMContext* context, char** str, PangoAttrList** attrs, int* cursor_pos);
extern gboolean _rgtk4_cb_filter_keypress(GtkIMContext* context, GdkEvent* event);
extern void _rgtk4_cb_focus_in(GtkIMContext* context);
extern void _rgtk4_cb_focus_out(GtkIMContext* context);
extern void _rgtk4_cb_set_cursor_location(GtkIMContext* context, GdkRectangle* area);
extern void _rgtk4_cb_set_use_preedit(GtkIMContext* context, gboolean use_preedit);
extern void _rgtk4_cb_set_surrounding(GtkIMContext* context, const char* text, int len, int cursor_index);
extern gboolean _rgtk4_cb_get_surrounding(GtkIMContext* context, char** text, int* cursor_index);
extern void _rgtk4_cb_set_surrounding_with_selection(GtkIMContext* context, const char* text, int len, int cursor_index, int anchor_index);
extern gboolean _rgtk4_cb_get_surrounding_with_selection(GtkIMContext* context, char** text, int* cursor_index, int* anchor_index);
extern void _rgtk4_cb_activate_osk(GtkIMContext* context);
extern gboolean _rgtk4_cb_activate_osk_with_event(GtkIMContext* context, GdkEvent* event);
extern gboolean _rgtk4_cb_invalid_composition(GtkIMContext* context, const char* str);
extern void _rgtk4_cb_IconViewForeachFunc(GtkIconView* icon_view, GtkTreePath* path, gpointer data);
extern void _rgtk4_cb_measure(GtkWidget* widget, GtkOrientation orientation, int for_size, int* minimum, int* natural, int* minimum_baseline, int* natural_baseline);
extern GtkLayoutChild* _rgtk4_cb_create_layout_child(GtkLayoutManager* manager, GtkWidget* widget, GtkWidget* for_child);
extern void _rgtk4_cb_root(GtkWidget* widget);
extern void _rgtk4_cb_unroot(GtkWidget* widget);
extern GtkWidget* _rgtk4_cb_ListBoxCreateWidgetFunc(gpointer item, gpointer user_data);
extern gboolean _rgtk4_cb_ListBoxFilterFunc(GtkListBoxRow* row, gpointer user_data);
extern void _rgtk4_cb_ListBoxForeachFunc(GtkListBox* box, GtkListBoxRow* row, gpointer user_data);
extern int _rgtk4_cb_ListBoxSortFunc(GtkListBoxRow* row1, GtkListBoxRow* row2, gpointer user_data);
extern void _rgtk4_cb_ListBoxUpdateHeaderFunc(GtkListBoxRow* row, GtkListBoxRow* before, gpointer user_data);
extern gpointer _rgtk4_cb_MapListModelMapFunc(gpointer item, gpointer user_data);
extern gboolean _rgtk4_cb_play(GtkMediaStream* self);
extern void _rgtk4_cb_pause(GtkMediaStream* self);
extern void _rgtk4_cb_update_audio(GtkMediaStream* self, gboolean muted, double volume);
extern void _rgtk4_cb_realize(GtkWidget* widget);
extern void _rgtk4_cb_unrealize(GtkWidget* widget);
extern void _rgtk4_cb_MenuButtonCreatePopupFunc(GtkMenuButton* menu_button, gpointer user_data);
extern void _rgtk4_cb_show(GtkWidget* widget);
extern void _rgtk4_cb_hide(GtkWidget* widget);
extern void _rgtk4_cb_closed(GdkPixbufLoader* loader);
extern void _rgtk4_cb_activate_default(GtkWindow* window);
extern gboolean _rgtk4_cb_is_selected(GtkSelectionModel* model, guint position);
extern void _rgtk4_cb_PrintSettingsFunc(const char* key, const char* value, gpointer user_data);
extern void _rgtk4_cb_adjust_bounds(GtkRange* range, double new_value);
extern void _rgtk4_cb_move_slider(GtkRange* range, GtkScrollType scroll);
extern void _rgtk4_cb_get_range_border(GtkRange* range, GtkBorder* border_);
extern gboolean _rgtk4_cb_change_value(GtkRange* range, GtkScrollType scroll, double new_value);
extern void _rgtk4_cb__gtk_recent1(void);
extern void _rgtk4_cb__gtk_recent2(void);
extern void _rgtk4_cb__gtk_recent3(void);
extern void _rgtk4_cb__gtk_recent4(void);
extern void _rgtk4_cb_get_layout_offsets(GtkScale* scale, int* x, int* y);
extern char* _rgtk4_cb_ScaleFormatValueFunc(GtkScale* scale, double value, gpointer user_data);
extern gboolean _rgtk4_cb_get_border(GtkScrollable* scrollable, GtkBorder* border);
extern void _rgtk4_cb_get_section(GtkSectionModel* self, guint position, guint* out_start, guint* out_end);
extern GtkBitset* _rgtk4_cb_get_selection_in_range(GtkSelectionModel* model, guint position, guint n_items);
extern gboolean _rgtk4_cb_select_item(GtkSelectionModel* model, guint position, gboolean unselect_rest);
extern gboolean _rgtk4_cb_unselect_item(GtkSelectionModel* model, guint position);
extern gboolean _rgtk4_cb_select_range(GtkSelectionModel* model, guint position, guint n_items, gboolean unselect_rest);
extern gboolean _rgtk4_cb_unselect_range(GtkSelectionModel* model, guint position, guint n_items);
extern gboolean _rgtk4_cb_select_all(GtkTreeView* tree_view);
extern gboolean _rgtk4_cb_unselect_all(GtkTreeView* tree_view);
extern gboolean _rgtk4_cb_ShortcutFunc(GtkWidget* widget, GVariant* args, gpointer user_data);
extern void _rgtk4_cb_add_controller(GtkShortcutManager* self, GtkShortcutController* controller);
extern void _rgtk4_cb_remove_controller(GtkShortcutManager* self, GtkShortcutController* controller);
extern GtkOrdering _rgtk4_cb_compare(GtkSorter* self, gpointer item1, gpointer item2);
extern GtkSorterOrder _rgtk4_cb_get_order(GtkSorter* self);
extern void _rgtk4_cb_snapshot_symbolic(GtkSymbolicPaintable* paintable, GdkSnapshot* snapshot, double width, double height, const GdkRGBA* colors, gsize n_colors);
extern void _rgtk4_cb_snapshot_with_weight(GtkSymbolicPaintable* paintable, GdkSnapshot* snapshot, double width, double height, const GdkRGBA* colors, gsize n_colors, double weight);
extern void _rgtk4_cb_insert_paintable(GtkTextBuffer* buffer, GtkTextIter* iter, GdkPaintable* paintable);
extern void _rgtk4_cb_insert_child_anchor(GtkTextBuffer* buffer, GtkTextIter* iter, GtkTextChildAnchor* anchor);
extern void _rgtk4_cb_delete_range(GtkTextBuffer* buffer, GtkTextIter* start, GtkTextIter* end);
extern void _rgtk4_cb_modified_changed(GtkTextBuffer* buffer);
extern void _rgtk4_cb_mark_set(GtkTextBuffer* buffer, const GtkTextIter* location, GtkTextMark* mark);
extern void _rgtk4_cb_mark_deleted(GtkTextBuffer* buffer, GtkTextMark* mark);
extern void _rgtk4_cb_apply_tag(GtkTextBuffer* buffer, GtkTextTag* tag, const GtkTextIter* start, const GtkTextIter* end);
extern void _rgtk4_cb_remove_tag(GtkTextBuffer* buffer, GtkTextTag* tag, const GtkTextIter* start, const GtkTextIter* end);
extern void _rgtk4_cb_begin_user_action(GtkTextBuffer* buffer);
extern void _rgtk4_cb_end_user_action(GtkTextBuffer* buffer);
extern void _rgtk4_cb_paste_done(GtkTextBuffer* buffer, GdkClipboard* clipboard);
extern void _rgtk4_cb_undo(GtkTextBuffer* buffer);
extern void _rgtk4_cb_redo(GtkTextBuffer* buffer);
extern gboolean _rgtk4_cb_TextCharPredicate(gunichar ch, gpointer user_data);
extern void _rgtk4_cb_TextTagTableForeach(GtkTextTag* tag, gpointer data);
extern gboolean _rgtk4_cb_move_cursor(GtkTreeView* tree_view, GtkMovementStep step, int count, gboolean extend, gboolean modify);
extern void _rgtk4_cb_set_anchor(GtkTextView* text_view);
extern void _rgtk4_cb_insert_at_cursor(GtkTextView* text_view, const char* str);
extern void _rgtk4_cb_delete_from_cursor(GtkTextView* text_view, GtkDeleteType type, int count);
extern void _rgtk4_cb_backspace(GtkTextView* text_view);
extern void _rgtk4_cb_cut_clipboard(GtkTextView* text_view);
extern void _rgtk4_cb_copy_clipboard(GtkTextView* text_view);
extern void _rgtk4_cb_paste_clipboard(GtkTextView* text_view);
extern void _rgtk4_cb_toggle_overwrite(GtkTextView* text_view);
extern void _rgtk4_cb_snapshot_layer(GtkTextView* text_view, GtkTextViewLayer layer, GtkSnapshot* snapshot);
extern gboolean _rgtk4_cb_extend_selection(GtkTextView* text_view, GtkTextExtendSelection granularity, const GtkTextIter* location, GtkTextIter* start, GtkTextIter* end);
extern void _rgtk4_cb_insert_emoji(GtkTextView* text_view);
extern gboolean _rgtk4_cb_TickCallback(GtkWidget* widget, GdkFrameClock* frame_clock, gpointer user_data);
extern void _rgtk4_cb_TreeCellDataFunc(GtkTreeViewColumn* tree_column, GtkCellRenderer* cell, GtkTreeModel* tree_model, GtkTreeIter* iter, gpointer data);
extern gboolean _rgtk4_cb_drag_data_received(GtkTreeDragDest* drag_dest, GtkTreePath* dest, const GValue* value);
extern gboolean _rgtk4_cb_row_drop_possible(GtkTreeDragDest* drag_dest, GtkTreePath* dest_path, const GValue* value);
extern gboolean _rgtk4_cb_row_draggable(GtkTreeDragSource* drag_source, GtkTreePath* path);
extern GdkContentProvider* _rgtk4_cb_drag_data_get(GtkTreeDragSource* drag_source, GtkTreePath* path);
extern gboolean _rgtk4_cb_drag_data_delete(GtkTreeDragSource* drag_source, GtkTreePath* path);
extern int _rgtk4_cb_TreeIterCompareFunc(GtkTreeModel* model, GtkTreeIter* a, GtkTreeIter* b, gpointer user_data);
extern GListModel* _rgtk4_cb_TreeListModelCreateModelFunc(gpointer item, gpointer user_data);
extern gboolean _rgtk4_cb_visible(GtkTreeModelFilter* self, GtkTreeModel* child_model, GtkTreeIter* iter);
extern void _rgtk4_cb_modify(GtkTreeModelFilter* self, GtkTreeModel* child_model, GtkTreeIter* iter, GValue* value, int column);
extern void _rgtk4_cb_TreeModelFilterModifyFunc(GtkTreeModel* model, GtkTreeIter* iter, GValue* value, int column, gpointer data);
extern gboolean _rgtk4_cb_TreeModelFilterVisibleFunc(GtkTreeModel* model, GtkTreeIter* iter, gpointer data);
extern gboolean _rgtk4_cb_TreeModelForeachFunc(GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer data);
extern void _rgtk4_cb_row_changed(GtkTreeModel* tree_model, GtkTreePath* path, GtkTreeIter* iter);
extern void _rgtk4_cb_row_inserted(GtkTreeModel* tree_model, GtkTreePath* path, GtkTreeIter* iter);
extern void _rgtk4_cb_row_has_child_toggled(GtkTreeModel* tree_model, GtkTreePath* path, GtkTreeIter* iter);
extern void _rgtk4_cb_row_deleted(GtkTreeModel* tree_model, GtkTreePath* path);
extern void _rgtk4_cb_rows_reordered(GtkTreeModel* tree_model, GtkTreePath* path, GtkTreeIter* iter, int* new_order);
extern int _rgtk4_cb_get_n_columns(GtkTreeModel* tree_model);
extern GType _rgtk4_cb_get_column_type(GtkTreeModel* tree_model, int index_);
extern GdkPixbufAnimationIter* _rgtk4_cb_get_iter(GdkPixbufAnimation* animation, const GTimeVal* start_time);
extern gboolean _rgtk4_cb_iter_next(GtkTreeModel* tree_model, GtkTreeIter* iter);
extern gboolean _rgtk4_cb_iter_previous(GtkTreeModel* tree_model, GtkTreeIter* iter);
extern gboolean _rgtk4_cb_iter_children(GtkTreeModel* tree_model, GtkTreeIter* iter, GtkTreeIter* parent);
extern gboolean _rgtk4_cb_iter_has_child(GtkTreeModel* tree_model, GtkTreeIter* iter);
extern int _rgtk4_cb_iter_n_children(GtkTreeModel* tree_model, GtkTreeIter* iter);
extern gboolean _rgtk4_cb_iter_nth_child(GtkTreeModel* tree_model, GtkTreeIter* iter, GtkTreeIter* parent, int n);
extern gboolean _rgtk4_cb_iter_parent(GtkTreeModel* tree_model, GtkTreeIter* iter, GtkTreeIter* child);
extern void _rgtk4_cb_ref_node(GtkTreeModel* tree_model, GtkTreeIter* iter);
extern void _rgtk4_cb_unref_node(GtkTreeModel* tree_model, GtkTreeIter* iter);
extern void _rgtk4_cb_TreeSelectionForeachFunc(GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer data);
extern gboolean _rgtk4_cb_TreeSelectionFunc(GtkTreeSelection* selection, GtkTreeModel* model, GtkTreePath* path, gboolean path_currently_selected, gpointer data);
extern void _rgtk4_cb_sort_column_changed(GtkTreeSortable* sortable);
extern gboolean _rgtk4_cb_get_sort_column_id(GtkTreeSortable* sortable, int* sort_column_id, GtkSortType* order);
extern void _rgtk4_cb_set_sort_column_id(GtkTreeSortable* sortable, int sort_column_id, GtkSortType order);
extern void _rgtk4_cb_set_sort_func(GtkTreeSortable* sortable, int sort_column_id, GtkTreeIterCompareFunc sort_func, gpointer user_data, GDestroyNotify destroy);
extern void _rgtk4_cb_set_default_sort_func(GtkTreeSortable* sortable, GtkTreeIterCompareFunc sort_func, gpointer user_data, GDestroyNotify destroy);
extern gboolean _rgtk4_cb_has_default_sort_func(GtkTreeSortable* sortable);
extern void _rgtk4_cb_row_activated(GtkTreeView* tree_view, GtkTreePath* path, GtkTreeViewColumn* column);
extern gboolean _rgtk4_cb_test_expand_row(GtkTreeView* tree_view, GtkTreeIter* iter, GtkTreePath* path);
extern gboolean _rgtk4_cb_test_collapse_row(GtkTreeView* tree_view, GtkTreeIter* iter, GtkTreePath* path);
extern void _rgtk4_cb_row_expanded(GtkTreeView* tree_view, GtkTreeIter* iter, GtkTreePath* path);
extern void _rgtk4_cb_row_collapsed(GtkTreeView* tree_view, GtkTreeIter* iter, GtkTreePath* path);
extern void _rgtk4_cb_columns_changed(GtkTreeView* tree_view);
extern void _rgtk4_cb_cursor_changed(GtkTreeView* tree_view);
extern gboolean _rgtk4_cb_select_cursor_row(GtkTreeView* tree_view, gboolean start_editing);
extern gboolean _rgtk4_cb_toggle_cursor_row(GtkTreeView* tree_view);
extern gboolean _rgtk4_cb_expand_collapse_cursor_row(GtkTreeView* tree_view, gboolean logical, gboolean expand, gboolean open_all);
extern gboolean _rgtk4_cb_select_cursor_parent(GtkTreeView* tree_view);
extern gboolean _rgtk4_cb_start_interactive_search(GtkTreeView* tree_view);
extern gboolean _rgtk4_cb_TreeViewColumnDropFunc(GtkTreeView* tree_view, GtkTreeViewColumn* column, GtkTreeViewColumn* prev_column, GtkTreeViewColumn* next_column, gpointer data);
extern void _rgtk4_cb_TreeViewMappingFunc(GtkTreeView* tree_view, GtkTreePath* path, gpointer user_data);
extern gboolean _rgtk4_cb_TreeViewRowSeparatorFunc(GtkTreeModel* model, GtkTreeIter* iter, gpointer data);
extern gboolean _rgtk4_cb_TreeViewSearchEqualFunc(GtkTreeModel* model, int column, const char* key, GtkTreeIter* iter, gpointer search_data);
extern void _rgtk4_cb_WidgetActionActivateFunc(GtkWidget* widget, const char* action_name, GVariant* parameter);
extern void _rgtk4_cb_map(GtkWidget* widget);
extern void _rgtk4_cb_unmap(GtkWidget* widget);
extern void _rgtk4_cb_size_allocate(GtkWidget* widget, int width, int height, int baseline);
extern void _rgtk4_cb_state_flags_changed(GtkWidget* widget, GtkStateFlags previous_state_flags);
extern void _rgtk4_cb_direction_changed(GtkWidget* widget, GtkTextDirection previous_direction);
extern gboolean _rgtk4_cb_mnemonic_activate(GtkWidget* widget, gboolean group_cycling);
extern gboolean _rgtk4_cb_grab_focus(GtkWidget* widget);
extern void _rgtk4_cb_set_focus_child(GtkWidget* widget, GtkWidget* child);
extern void _rgtk4_cb_move_focus(GtkWidget* widget, GtkDirectionType direction);
extern gboolean _rgtk4_cb_keynav_failed(GtkWidget* widget, GtkDirectionType direction);
extern gboolean _rgtk4_cb_query_tooltip(GtkWidget* widget, int x, int y, gboolean keyboard_tooltip, GtkTooltip* tooltip);
extern void _rgtk4_cb_compute_expand(GtkWidget* widget, gboolean* hexpand_p, gboolean* vexpand_p);
extern void _rgtk4_cb_css_changed(GtkWidget* widget, GtkCssStyleChange* change);
extern void _rgtk4_cb_system_setting_changed(GtkWidget* widget, GtkSystemSetting settings);
extern gboolean _rgtk4_cb_contains(GtkWidget* widget, double x, double y);
extern void _rgtk4_cb_activate_focus(GtkWindow* window);
extern void _rgtk4_cb_keys_changed(GtkWindow* window);
extern gboolean _rgtk4_cb_enable_debugging(GtkWindow* window, gboolean toggle);
extern gboolean _rgtk4_cb_close_request(GtkWindow* window);
extern void _rgtk4_cb_destroy(PangoAttribute* attr);
extern gpointer _rgtk4_cb_AttrDataCopyFunc(gconstpointer user_data);
extern gboolean _rgtk4_cb_AttrFilterFunc(PangoAttribute* attribute, gpointer user_data);
extern PangoFontDescription* _rgtk4_cb_describe(PangoFontFace* face);
extern PangoCoverage* _rgtk4_cb_get_coverage(PangoFont* font, PangoLanguage* language);
extern void _rgtk4_cb_get_glyph_extents(PangoFont* font, PangoGlyph glyph, PangoRectangle* ink_rect, PangoRectangle* logical_rect);
extern PangoFontMetrics* _rgtk4_cb_get_metrics(PangoFontset* fontset);
extern PangoFontDescription* _rgtk4_cb_describe_absolute(PangoFont* font);
extern void _rgtk4_cb_get_features(PangoFont* font, hb_feature_t* features, guint len, guint* num_features);
extern hb_font_t* _rgtk4_cb_create_hb_font(PangoFont* font);
extern const char* _rgtk4_cb_get_face_name(PangoFontFace* face);
extern void _rgtk4_cb_list_sizes(PangoFontFace* face, int** sizes, int* n_sizes);
extern gboolean _rgtk4_cb_is_synthesized(PangoFontFace* face);
extern void _rgtk4_cb__pango_reserved3(void);
extern void _rgtk4_cb__pango_reserved4(void);
extern void _rgtk4_cb_list_faces(PangoFontFamily* family, PangoFontFace*** faces, int* n_faces);
extern gboolean _rgtk4_cb_is_monospace(PangoFontFamily* family);
extern gboolean _rgtk4_cb_is_variable(PangoFontFamily* family);
extern PangoFontFace* _rgtk4_cb_get_face(PangoFontFamily* family, const char* name);
extern void _rgtk4_cb__pango_reserved2(void);
extern PangoFont* _rgtk4_cb_load_font(PangoFontMap* fontmap, PangoContext* context, const PangoFontDescription* desc);
extern void _rgtk4_cb_list_families(PangoFontMap* fontmap, PangoFontFamily*** families, int* n_families);
extern PangoFontset* _rgtk4_cb_load_fontset(PangoFontMap* fontmap, PangoContext* context, const PangoFontDescription* desc, PangoLanguage* language);
extern guint _rgtk4_cb_get_serial(PangoFontMap* fontmap);
extern PangoFont* _rgtk4_cb_get_font(PangoFontset* fontset, guint wc);
extern PangoLanguage* _rgtk4_cb_get_language(PangoFontset* fontset);
extern void _rgtk4_cb__pango_reserved1(void);
extern gboolean _rgtk4_cb_FontsetForeachFunc(PangoFontset* fontset, PangoFont* font, gpointer user_data);
extern void _rgtk4_cb_draw_glyphs(PangoRenderer* renderer, PangoFont* font, PangoGlyphString* glyphs, int x, int y);
extern void _rgtk4_cb_draw_rectangle(PangoRenderer* renderer, PangoRenderPart part, int x, int y, int width, int height);
extern void _rgtk4_cb_draw_error_underline(PangoRenderer* renderer, int x, int y, int width, int height);
extern void _rgtk4_cb_draw_shape(PangoRenderer* renderer, PangoAttrShape* attr, int x, int y);
extern void _rgtk4_cb_draw_trapezoid(PangoRenderer* renderer, PangoRenderPart part, double y1_, double x11, double x21, double y2, double x12, double x22);
extern void _rgtk4_cb_draw_glyph(PangoRenderer* renderer, PangoFont* font, PangoGlyph glyph, double x, double y);
extern void _rgtk4_cb_part_changed(PangoRenderer* renderer, PangoRenderPart part);
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_begin(GtkSourceGutterRenderer* renderer, GtkSourceGutterLines* lines);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_end(GtkSourceGutterRenderer* renderer);
#endif
extern void _rgtk4_cb_prepare_run(PangoRenderer* renderer, PangoLayoutRun* run);
extern void _rgtk4_cb_draw_glyph_item(PangoRenderer* renderer, const char* text, PangoGlyphItem* glyph_item, int x, int y);
extern gboolean _rgtk4_cb_is_static_image(GdkPixbufAnimation* animation);
extern GdkPixbuf* _rgtk4_cb_get_static_image(GdkPixbufAnimation* animation);
extern int _rgtk4_cb_get_delay_time(GdkPixbufAnimationIter* iter);
extern GdkPixbuf* _rgtk4_cb_get_pixbuf(GdkPixbufAnimationIter* iter);
extern gboolean _rgtk4_cb_on_currently_loading_frame(GdkPixbufAnimationIter* iter);
extern gboolean _rgtk4_cb_advance(GdkPixbufAnimationIter* iter, const GTimeVal* current_time);
extern void _rgtk4_cb_PixbufDestroyNotify(guchar* pixels, gpointer data);
extern void _rgtk4_cb_size_prepared(GdkPixbufLoader* loader, int width, int height);
extern void _rgtk4_cb_area_prepared(GdkPixbufLoader* loader);
extern void _rgtk4_cb_area_updated(GdkPixbufLoader* loader, int x, int y, int width, int height);
extern void _rgtk4_cb__reserved1(void);
extern void _rgtk4_cb__reserved2(void);
extern void _rgtk4_cb__reserved3(void);
extern void _rgtk4_cb__reserved4(void);
extern void _rgtk4_cb_PixbufModuleFillInfoFunc(GdkPixbufFormat* info);
extern GdkPixbuf* _rgtk4_cb_PixbufModuleLoadXpmDataFunc(const char** data);
extern void _rgtk4_cb_PixbufModulePreparedFunc(GdkPixbuf* pixbuf, GdkPixbufAnimation* anim, gpointer user_data);
extern gboolean _rgtk4_cb_PixbufModuleSaveOptionSupportedFunc(const gchar* option_key);
extern void _rgtk4_cb_PixbufModuleSizeFunc(gint* width, gint* height, gpointer user_data);
extern void _rgtk4_cb_PixbufModuleUpdatedFunc(GdkPixbuf* pixbuf, int x, int y, int width, int height, gpointer user_data);
extern gboolean _rgtk4_cb_PixbufSaveFunc(const gchar* buf, gsize count, GError** error, gpointer data);
extern void _rgtk4_cb_ParseErrorFunc(const GskParseLocation* start, const GskParseLocation* end, const GError* error, gpointer user_data);
extern gboolean _rgtk4_cb_PathForeachFunc(GskPathOperation op, const graphene_point_t* pts, gsize n_pts, float weight, gpointer user_data);
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_populate_hover_async(GtkSourceAnnotationProvider* self, GtkSourceAnnotation* annotation, GtkSourceHoverDisplay* display, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_bracket_matched(GtkSourceBuffer* buffer, GtkTextIter* iter, GtkSourceBracketMatchType state);
#endif
#ifdef HAVE_GTKSOURCE
extern char* _rgtk4_cb_get_typed_text(GtkSourceCompletionProposal* proposal);
#endif
#ifdef HAVE_GTKSOURCE
extern char* _rgtk4_cb_get_title(GtkSourceCompletionProvider* self);
#endif
#ifdef HAVE_GTKSOURCE
extern int _rgtk4_cb_get_priority(GtkSourceCompletionProvider* self, GtkSourceCompletionContext* context);
#endif
#ifdef HAVE_GTKSOURCE
extern gboolean _rgtk4_cb_is_trigger(GtkSourceIndenter* self, GtkSourceView* view, const GtkTextIter* location, GdkModifierType state, guint keyval);
#endif
#ifdef HAVE_GTKSOURCE
extern gboolean _rgtk4_cb_key_activates(GtkSourceCompletionProvider* self, GtkSourceCompletionContext* context, GtkSourceCompletionProposal* proposal, guint keyval, GdkModifierType state);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_populate_async(GtkSourceHoverProvider* self, GtkSourceHoverContext* context, GtkSourceHoverDisplay* display, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_refilter(GtkSourceCompletionProvider* self, GtkSourceCompletionContext* context, GListModel* model);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_display(GtkSourceCompletionProvider* self, GtkSourceCompletionContext* context, GtkSourceCompletionProposal* proposal, GtkSourceCompletionCell* cell);
#endif
#ifdef HAVE_GTKSOURCE
extern GPtrArray* _rgtk4_cb_list_alternates(GtkSourceCompletionProvider* self, GtkSourceCompletionContext* context, GtkSourceCompletionProposal* proposal);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_query_data(GtkSourceGutterRenderer* renderer, GtkSourceGutterLines* lines, guint line);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_snapshot_line(GtkSourceGutterRenderer* renderer, GtkSnapshot* snapshot, GtkSourceGutterLines* lines, guint line);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_change_view(GtkSourceGutterRenderer* renderer, GtkSourceView* old_view);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_change_buffer(GtkSourceGutterRenderer* renderer, GtkSourceBuffer* old_buffer);
#endif
#ifdef HAVE_GTKSOURCE
extern gboolean _rgtk4_cb_query_activatable(GtkSourceGutterRenderer* renderer, GtkTextIter* iter, GdkRectangle* area);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_indent(GtkSourceIndenter* self, GtkSourceView* view, GtkTextIter* iter);
#endif
#ifdef HAVE_GTKSOURCE
extern gboolean _rgtk4_cb_SchedulerCallback(gint64 deadline, gpointer user_data);
#endif
#ifdef HAVE_GTKSOURCE
extern GtkSourceStyleScheme* _rgtk4_cb_get_style_scheme(GtkSourceStyleSchemeChooser* chooser);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_set_style_scheme(GtkSourceStyleSchemeChooser* chooser, GtkSourceStyleScheme* scheme);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_line_mark_activated(GtkSourceView* view, const GtkTextIter* iter, guint button, GdkModifierType state, gint n_presses);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_show_completion(GtkSourceView* view);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_move_lines(GtkSourceView* view, gboolean down);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_move_words(GtkSourceView* view, gint step);
#endif
#ifdef HAVE_GTKSOURCE
extern void _rgtk4_cb_push_snippet(GtkSourceView* view, GtkSourceSnippet* snippet, GtkTextIter* location);
#endif

#pragma GCC diagnostic pop

#endif
