/* rgtk4_gtksource_probe.c
 *
 * Hand-written (NOT autogenerated). Always compiled, regardless of whether
 * GtkSourceView is available. Lets R code query at runtime whether the
 * GtkSource bindings were compiled in, so gtkSource* wrappers can raise a
 * clear error instead of failing with an unresolved-symbol message.
 *
 * Add to src/ and to the list of files copied manually after generation.
 * The {"R_have_gtksource", ...} entry in init.c is produced automatically
 * by Generate_init.R, which scans for ^SEXP R_ definitions.
 */

#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>

SEXP R_have_gtksource(void) {
#ifdef HAVE_GTKSOURCE
  return Rf_ScalarLogical(1);
#else
  return Rf_ScalarLogical(0);
#endif
}
