# Autogenerated R wrappers

#' @rdname gdk-graphics
#' @title gdkPixbufNew
#'
#' @param colorspace Colorspace
#' @param has_alpha gboolean
#' @param bits_per_sample gint
#' @param width gint
#' @param height gint
#' @return Pixbuf
#' @export
gdkPixbufNew <- function(colorspace, has_alpha, bits_per_sample, width, height) {
  .Call("R_gdk_pixbuf_new", colorspace, has_alpha, as.integer(bits_per_sample), as.integer(width), as.integer(height))$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromBytes
#'
#' @param data GLib.Bytes
#' @param colorspace Colorspace
#' @param has_alpha gboolean
#' @param bits_per_sample gint
#' @param width gint
#' @param height gint
#' @param rowstride gint
#' @return Pixbuf
#' @export
gdkPixbufNewFromBytes <- function(data, colorspace, has_alpha, bits_per_sample, width, height, rowstride) {
  .Call("R_gdk_pixbuf_new_from_bytes", data, colorspace, has_alpha, as.integer(bits_per_sample), as.integer(width), as.integer(height), as.integer(rowstride))$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromData
#'
#' @param data guint8
#' @param colorspace Colorspace
#' @param has_alpha gboolean
#' @param bits_per_sample gint
#' @param width gint
#' @param height gint
#' @param rowstride gint
#' @param destroy_fn PixbufDestroyNotify
#' @param destroy_fn_data gpointer
#' @return Pixbuf
#' @export
gdkPixbufNewFromData <- function(data, colorspace, has_alpha, bits_per_sample, width, height, rowstride, destroy_fn, destroy_fn_data) {
  .Call("R_gdk_pixbuf_new_from_data", data, colorspace, has_alpha, as.integer(bits_per_sample), as.integer(width), as.integer(height), as.integer(rowstride), destroy_fn, destroy_fn_data)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromFile
#'
#' @param filename filename
#' @return Pixbuf
#' @export
gdkPixbufNewFromFile <- function(filename) {
  .Call("R_gdk_pixbuf_new_from_file", filename)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromFileAtScale
#'
#' @param filename filename
#' @param width gint
#' @param height gint
#' @param preserve_aspect_ratio gboolean
#' @return Pixbuf
#' @export
gdkPixbufNewFromFileAtScale <- function(filename, width, height, preserve_aspect_ratio) {
  .Call("R_gdk_pixbuf_new_from_file_at_scale", filename, as.integer(width), as.integer(height), preserve_aspect_ratio)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromFileAtSize
#'
#' @param filename filename
#' @param width gint
#' @param height gint
#' @return Pixbuf
#' @export
gdkPixbufNewFromFileAtSize <- function(filename, width, height) {
  .Call("R_gdk_pixbuf_new_from_file_at_size", filename, as.integer(width), as.integer(height))$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromInline
#'
#' @param data_length gint
#' @param data guint8
#' @param copy_pixels gboolean
#' @return Pixbuf
#' @export
gdkPixbufNewFromInline <- function(data_length, data, copy_pixels) {
  .Call("R_gdk_pixbuf_new_from_inline", as.integer(data_length), data, copy_pixels)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromResource
#'
#' @param resource_path utf8
#' @return Pixbuf
#' @export
gdkPixbufNewFromResource <- function(resource_path) {
  .Call("R_gdk_pixbuf_new_from_resource", resource_path)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromResourceAtScale
#'
#' @param resource_path utf8
#' @param width gint
#' @param height gint
#' @param preserve_aspect_ratio gboolean
#' @return Pixbuf
#' @export
gdkPixbufNewFromResourceAtScale <- function(resource_path, width, height, preserve_aspect_ratio) {
  .Call("R_gdk_pixbuf_new_from_resource_at_scale", resource_path, as.integer(width), as.integer(height), preserve_aspect_ratio)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromStream
#'
#' @param stream Gio.InputStream
#' @param cancellable Gio.Cancellable
#' @return Pixbuf
#' @export
gdkPixbufNewFromStream <- function(stream, cancellable) {
  .Call("R_gdk_pixbuf_new_from_stream", stream, cancellable)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromStreamAtScale
#'
#' @param stream Gio.InputStream
#' @param width gint
#' @param height gint
#' @param preserve_aspect_ratio gboolean
#' @param cancellable Gio.Cancellable
#' @return Pixbuf
#' @export
gdkPixbufNewFromStreamAtScale <- function(stream, width, height, preserve_aspect_ratio, cancellable) {
  .Call("R_gdk_pixbuf_new_from_stream_at_scale", stream, as.integer(width), as.integer(height), preserve_aspect_ratio, cancellable)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromStreamFinish
#'
#' @param async_result Gio.AsyncResult
#' @return Pixbuf
#' @export
gdkPixbufNewFromStreamFinish <- function(async_result) {
  .Call("R_gdk_pixbuf_new_from_stream_finish", async_result)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromXpmData
#'
#' @param data utf8
#' @return Pixbuf
#' @export
gdkPixbufNewFromXpmData <- function(data) {
  .Call("R_gdk_pixbuf_new_from_xpm_data", data)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufCalculateRowstride
#'
#' @param colorspace Colorspace
#' @param has_alpha gboolean
#' @param bits_per_sample gint
#' @param width gint
#' @param height gint
#' @return gint
#' @export
gdkPixbufCalculateRowstride <- function(colorspace, has_alpha, bits_per_sample, width, height) {
  .Call("R_gdk_pixbuf_calculate_rowstride", colorspace, has_alpha, as.integer(bits_per_sample), as.integer(width), as.integer(height))$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetFileInfo
#'
#' @param filename filename
#' @return PixbufFormat
#' @export
gdkPixbufGetFileInfo <- function(filename) {
  .Call("R_gdk_pixbuf_get_file_info", filename)
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetFileInfoAsync
#'
#' @param filename filename
#' @param cancellable Gio.Cancellable
#' @param callback function — Gio.AsyncReadyCallback function(source_object, res)
#' @return Return value from C function
#' @export
gdkPixbufGetFileInfoAsync <- function(filename, cancellable, callback) {
  invisible(.Call("R_gdk_pixbuf_get_file_info_async", filename, cancellable, callback))
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetFileInfoFinish
#'
#' @param async_result Gio.AsyncResult
#' @return PixbufFormat
#' @export
gdkPixbufGetFileInfoFinish <- function(async_result) {
  .Call("R_gdk_pixbuf_get_file_info_finish", async_result)
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetFormats
#'
#' @return GLib.SList
#' @export
gdkPixbufGetFormats <- function() {
  .Call("R_gdk_pixbuf_get_formats")$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufInitModules
#'
#' @param path utf8
#' @return gboolean
#' @export
gdkPixbufInitModules <- function(path) {
  .Call("R_gdk_pixbuf_init_modules", path)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromStreamAsync
#'
#' @param stream Gio.InputStream
#' @param cancellable Gio.Cancellable
#' @param callback function — Gio.AsyncReadyCallback function(source_object, res)
#' @return Return value from C function
#' @export
gdkPixbufNewFromStreamAsync <- function(stream, cancellable, callback) {
  invisible(.Call("R_gdk_pixbuf_new_from_stream_async", stream, cancellable, callback))
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewFromStreamAtScaleAsync
#'
#' @param stream Gio.InputStream
#' @param width gint
#' @param height gint
#' @param preserve_aspect_ratio gboolean
#' @param cancellable Gio.Cancellable
#' @param callback function — Gio.AsyncReadyCallback function(source_object, res)
#' @return Return value from C function
#' @export
gdkPixbufNewFromStreamAtScaleAsync <- function(stream, width, height, preserve_aspect_ratio, cancellable, callback) {
  invisible(.Call("R_gdk_pixbuf_new_from_stream_at_scale_async", stream, as.integer(width), as.integer(height), preserve_aspect_ratio, cancellable, callback))
}


#' @rdname gdk-graphics
#' @title gdkPixbufSaveToStreamFinish
#'
#' @param async_result Gio.AsyncResult
#' @return gboolean
#' @export
gdkPixbufSaveToStreamFinish <- function(async_result) {
  .Call("R_gdk_pixbuf_save_to_stream_finish", async_result)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAddAlpha
#'
#' @param pixbuf Pixbuf
#' @param substitute_color gboolean
#' @param r guint8
#' @param g guint8
#' @param b guint8
#' @return Pixbuf
#' @export
gdkPixbufAddAlpha <- function(pixbuf, substitute_color, r, g, b) {
  .Call("R_gdk_pixbuf_add_alpha", pixbuf, substitute_color, as.integer(r), as.integer(g), as.integer(b))$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufApplyEmbeddedOrientation
#'
#' @param src Pixbuf
#' @return Pixbuf
#' @export
gdkPixbufApplyEmbeddedOrientation <- function(src) {
  .Call("R_gdk_pixbuf_apply_embedded_orientation", src)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufComposite
#'
#' @param src Pixbuf
#' @param dest Pixbuf
#' @param dest_x gint
#' @param dest_y gint
#' @param dest_width gint
#' @param dest_height gint
#' @param offset_x gdouble
#' @param offset_y gdouble
#' @param scale_x gdouble
#' @param scale_y gdouble
#' @param interp_type InterpType
#' @param overall_alpha gint
#' @return Return value from C function
#' @export
gdkPixbufComposite <- function(src, dest, dest_x, dest_y, dest_width, dest_height, offset_x, offset_y, scale_x, scale_y, interp_type, overall_alpha) {
  invisible(.Call("R_gdk_pixbuf_composite", src, dest, as.integer(dest_x), as.integer(dest_y), as.integer(dest_width), as.integer(dest_height), offset_x, offset_y, scale_x, scale_y, interp_type, as.integer(overall_alpha)))
}


#' @rdname gdk-graphics
#' @title gdkPixbufCompositeColor
#'
#' @param src Pixbuf
#' @param dest Pixbuf
#' @param dest_x gint
#' @param dest_y gint
#' @param dest_width gint
#' @param dest_height gint
#' @param offset_x gdouble
#' @param offset_y gdouble
#' @param scale_x gdouble
#' @param scale_y gdouble
#' @param interp_type InterpType
#' @param overall_alpha gint
#' @param check_x gint
#' @param check_y gint
#' @param check_size gint
#' @param color1 guint32
#' @param color2 guint32
#' @return Return value from C function
#' @export
gdkPixbufCompositeColor <- function(src, dest, dest_x, dest_y, dest_width, dest_height, offset_x, offset_y, scale_x, scale_y, interp_type, overall_alpha, check_x, check_y, check_size, color1, color2) {
  invisible(.Call("R_gdk_pixbuf_composite_color", src, dest, as.integer(dest_x), as.integer(dest_y), as.integer(dest_width), as.integer(dest_height), offset_x, offset_y, scale_x, scale_y, interp_type, as.integer(overall_alpha), as.integer(check_x), as.integer(check_y), as.integer(check_size), color1, color2))
}


#' @rdname gdk-graphics
#' @title gdkPixbufCompositeColorSimple
#'
#' @param src Pixbuf
#' @param dest_width gint
#' @param dest_height gint
#' @param interp_type InterpType
#' @param overall_alpha gint
#' @param check_size gint
#' @param color1 guint32
#' @param color2 guint32
#' @return Pixbuf
#' @export
gdkPixbufCompositeColorSimple <- function(src, dest_width, dest_height, interp_type, overall_alpha, check_size, color1, color2) {
  .Call("R_gdk_pixbuf_composite_color_simple", src, as.integer(dest_width), as.integer(dest_height), interp_type, as.integer(overall_alpha), as.integer(check_size), color1, color2)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufCopy
#'
#' @param pixbuf Pixbuf
#' @return Pixbuf
#' @export
gdkPixbufCopy <- function(pixbuf) {
  .Call("R_gdk_pixbuf_copy", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufCopyArea
#'
#' @param src_pixbuf Pixbuf
#' @param src_x gint
#' @param src_y gint
#' @param width gint
#' @param height gint
#' @param dest_pixbuf Pixbuf
#' @param dest_x gint
#' @param dest_y gint
#' @return Return value from C function
#' @export
gdkPixbufCopyArea <- function(src_pixbuf, src_x, src_y, width, height, dest_pixbuf, dest_x, dest_y) {
  invisible(.Call("R_gdk_pixbuf_copy_area", src_pixbuf, as.integer(src_x), as.integer(src_y), as.integer(width), as.integer(height), dest_pixbuf, as.integer(dest_x), as.integer(dest_y)))
}


#' @rdname gdk-graphics
#' @title gdkPixbufCopyOptions
#'
#' @param src_pixbuf Pixbuf
#' @param dest_pixbuf Pixbuf
#' @return gboolean
#' @export
gdkPixbufCopyOptions <- function(src_pixbuf, dest_pixbuf) {
  .Call("R_gdk_pixbuf_copy_options", src_pixbuf, dest_pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFill
#'
#' @param pixbuf Pixbuf
#' @param pixel guint32
#' @return Return value from C function
#' @export
gdkPixbufFill <- function(pixbuf, pixel) {
  invisible(.Call("R_gdk_pixbuf_fill", pixbuf, pixel))
}


#' @rdname gdk-graphics
#' @title gdkPixbufFlip
#'
#' @param src Pixbuf
#' @param horizontal gboolean
#' @return Pixbuf
#' @export
gdkPixbufFlip <- function(src, horizontal) {
  .Call("R_gdk_pixbuf_flip", src, horizontal)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetBitsPerSample
#'
#' @param pixbuf Pixbuf
#' @return gint
#' @export
gdkPixbufGetBitsPerSample <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_bits_per_sample", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetByteLength
#'
#' @param pixbuf Pixbuf
#' @return gsize
#' @export
gdkPixbufGetByteLength <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_byte_length", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetColorspace
#'
#' @param pixbuf Pixbuf
#' @return Colorspace
#' @export
gdkPixbufGetColorspace <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_colorspace", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetHasAlpha
#'
#' @param pixbuf Pixbuf
#' @return gboolean
#' @export
gdkPixbufGetHasAlpha <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_has_alpha", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetHeight
#'
#' @param pixbuf Pixbuf
#' @return gint
#' @export
gdkPixbufGetHeight <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_height", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetNChannels
#'
#' @param pixbuf Pixbuf
#' @return gint
#' @export
gdkPixbufGetNChannels <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_n_channels", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetOption
#'
#' @param pixbuf Pixbuf
#' @param key utf8
#' @return utf8
#' @export
gdkPixbufGetOption <- function(pixbuf, key) {
  .Call("R_gdk_pixbuf_get_option", pixbuf, key)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetOptions
#'
#' @param pixbuf Pixbuf
#' @return GLib.HashTable
#' @export
gdkPixbufGetOptions <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_options", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetPixels
#'
#' @param pixbuf Pixbuf
#' @return guint8
#' @export
gdkPixbufGetPixels <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_pixels", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetPixelsWithLength
#'
#' @param pixbuf Pixbuf
#' @return guint8
#' @export
gdkPixbufGetPixelsWithLength <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_pixels_with_length", pixbuf)
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetRowstride
#'
#' @param pixbuf Pixbuf
#' @return gint
#' @export
gdkPixbufGetRowstride <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_rowstride", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufGetWidth
#'
#' @param pixbuf Pixbuf
#' @return gint
#' @export
gdkPixbufGetWidth <- function(pixbuf) {
  .Call("R_gdk_pixbuf_get_width", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufNewSubpixbuf
#'
#' @param src_pixbuf Pixbuf
#' @param src_x gint
#' @param src_y gint
#' @param width gint
#' @param height gint
#' @return Pixbuf
#' @export
gdkPixbufNewSubpixbuf <- function(src_pixbuf, src_x, src_y, width, height) {
  .Call("R_gdk_pixbuf_new_subpixbuf", src_pixbuf, as.integer(src_x), as.integer(src_y), as.integer(width), as.integer(height))$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufReadPixelBytes
#'
#' @param pixbuf Pixbuf
#' @return GLib.Bytes
#' @export
gdkPixbufReadPixelBytes <- function(pixbuf) {
  .Call("R_gdk_pixbuf_read_pixel_bytes", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufReadPixels
#'
#' @param pixbuf Pixbuf
#' @return guint8
#' @export
gdkPixbufReadPixels <- function(pixbuf) {
  .Call("R_gdk_pixbuf_read_pixels", pixbuf)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufRemoveOption
#'
#' @param pixbuf Pixbuf
#' @param key utf8
#' @return gboolean
#' @export
gdkPixbufRemoveOption <- function(pixbuf, key) {
  .Call("R_gdk_pixbuf_remove_option", pixbuf, key)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufRotateSimple
#'
#' @param src Pixbuf
#' @param angle PixbufRotation
#' @return Pixbuf
#' @export
gdkPixbufRotateSimple <- function(src, angle) {
  .Call("R_gdk_pixbuf_rotate_simple", src, angle)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufSaturateAndPixelate
#'
#' @param src Pixbuf
#' @param dest Pixbuf
#' @param saturation gfloat
#' @param pixelate gboolean
#' @return Return value from C function
#' @export
gdkPixbufSaturateAndPixelate <- function(src, dest, saturation, pixelate) {
  invisible(.Call("R_gdk_pixbuf_saturate_and_pixelate", src, dest, saturation, pixelate))
}


#' @rdname gdk-graphics
#' @title gdkPixbufSaveToBufferv
#'
#' @param pixbuf Pixbuf
#' @param type utf8
#' @param option_keys utf8
#' @param option_values utf8
#' @return gboolean
#' @export
gdkPixbufSaveToBufferv <- function(pixbuf, type, option_keys, option_values) {
  .Call("R_gdk_pixbuf_save_to_bufferv", pixbuf, type, option_keys, option_values)
}


#' @rdname gdk-graphics
#' @title gdkPixbufSaveToCallbackv
#'
#' @param pixbuf Pixbuf
#' @param save_func function — PixbufSaveFunc function(buf, count, error)
#' @param type utf8
#' @param option_keys utf8
#' @param option_values utf8
#' @return gboolean
#' @export
gdkPixbufSaveToCallbackv <- function(pixbuf, save_func, type, option_keys, option_values) {
  .Call("R_gdk_pixbuf_save_to_callbackv", pixbuf, save_func, type, option_keys, option_values)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufSaveToStreamv
#'
#' @param pixbuf Pixbuf
#' @param stream Gio.OutputStream
#' @param type utf8
#' @param option_keys utf8
#' @param option_values utf8
#' @param cancellable Gio.Cancellable
#' @return gboolean
#' @export
gdkPixbufSaveToStreamv <- function(pixbuf, stream, type, option_keys, option_values, cancellable) {
  .Call("R_gdk_pixbuf_save_to_streamv", pixbuf, stream, type, option_keys, option_values, cancellable)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufSaveToStreamvAsync
#'
#' @param pixbuf Pixbuf
#' @param stream Gio.OutputStream
#' @param type utf8
#' @param option_keys utf8
#' @param option_values utf8
#' @param cancellable Gio.Cancellable
#' @param callback function — Gio.AsyncReadyCallback function(source_object, res)
#' @return Return value from C function
#' @export
gdkPixbufSaveToStreamvAsync <- function(pixbuf, stream, type, option_keys, option_values, cancellable, callback) {
  invisible(.Call("R_gdk_pixbuf_save_to_streamv_async", pixbuf, stream, type, option_keys, option_values, cancellable, callback))
}


#' @rdname gdk-graphics
#' @title gdkPixbufSavev
#'
#' @param pixbuf Pixbuf
#' @param filename filename
#' @param type utf8
#' @param option_keys utf8
#' @param option_values utf8
#' @return gboolean
#' @export
gdkPixbufSavev <- function(pixbuf, filename, type, option_keys, option_values) {
  .Call("R_gdk_pixbuf_savev", pixbuf, filename, type, option_keys, option_values)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufScale
#'
#' @param src Pixbuf
#' @param dest Pixbuf
#' @param dest_x gint
#' @param dest_y gint
#' @param dest_width gint
#' @param dest_height gint
#' @param offset_x gdouble
#' @param offset_y gdouble
#' @param scale_x gdouble
#' @param scale_y gdouble
#' @param interp_type InterpType
#' @return Return value from C function
#' @export
gdkPixbufScale <- function(src, dest, dest_x, dest_y, dest_width, dest_height, offset_x, offset_y, scale_x, scale_y, interp_type) {
  invisible(.Call("R_gdk_pixbuf_scale", src, dest, as.integer(dest_x), as.integer(dest_y), as.integer(dest_width), as.integer(dest_height), offset_x, offset_y, scale_x, scale_y, interp_type))
}


#' @rdname gdk-graphics
#' @title gdkPixbufScaleSimple
#'
#' @param src Pixbuf
#' @param dest_width gint
#' @param dest_height gint
#' @param interp_type InterpType
#' @return Pixbuf
#' @export
gdkPixbufScaleSimple <- function(src, dest_width, dest_height, interp_type) {
  .Call("R_gdk_pixbuf_scale_simple", src, as.integer(dest_width), as.integer(dest_height), interp_type)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufSetOption
#'
#' @param pixbuf Pixbuf
#' @param key utf8
#' @param value utf8
#' @return gboolean
#' @export
gdkPixbufSetOption <- function(pixbuf, key, value) {
  .Call("R_gdk_pixbuf_set_option", pixbuf, key, value)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationNewFromFile
#'
#' @param filename filename
#' @return PixbufAnimation
#' @export
gdkPixbufAnimationNewFromFile <- function(filename) {
  .Call("R_gdk_pixbuf_animation_new_from_file", filename)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationNewFromResource
#'
#' @param resource_path utf8
#' @return PixbufAnimation
#' @export
gdkPixbufAnimationNewFromResource <- function(resource_path) {
  .Call("R_gdk_pixbuf_animation_new_from_resource", resource_path)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationNewFromStream
#'
#' @param stream Gio.InputStream
#' @param cancellable Gio.Cancellable
#' @return PixbufAnimation
#' @export
gdkPixbufAnimationNewFromStream <- function(stream, cancellable) {
  .Call("R_gdk_pixbuf_animation_new_from_stream", stream, cancellable)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationNewFromStreamFinish
#'
#' @param async_result Gio.AsyncResult
#' @return PixbufAnimation
#' @export
gdkPixbufAnimationNewFromStreamFinish <- function(async_result) {
  .Call("R_gdk_pixbuf_animation_new_from_stream_finish", async_result)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationNewFromStreamAsync
#'
#' @param stream Gio.InputStream
#' @param cancellable Gio.Cancellable
#' @param callback function — Gio.AsyncReadyCallback function(source_object, res)
#' @return Return value from C function
#' @export
gdkPixbufAnimationNewFromStreamAsync <- function(stream, cancellable, callback) {
  invisible(.Call("R_gdk_pixbuf_animation_new_from_stream_async", stream, cancellable, callback))
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationGetHeight
#'
#' @param animation PixbufAnimation
#' @return gint
#' @export
gdkPixbufAnimationGetHeight <- function(animation) {
  .Call("R_gdk_pixbuf_animation_get_height", animation)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationGetIter
#'
#' @param animation PixbufAnimation
#' @param start_time GLib.TimeVal
#' @return PixbufAnimationIter
#' @export
gdkPixbufAnimationGetIter <- function(animation, start_time) {
  .Call("R_gdk_pixbuf_animation_get_iter", animation, start_time)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationGetStaticImage
#'
#' @param animation PixbufAnimation
#' @return Pixbuf
#' @export
gdkPixbufAnimationGetStaticImage <- function(animation) {
  .Call("R_gdk_pixbuf_animation_get_static_image", animation)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationGetWidth
#'
#' @param animation PixbufAnimation
#' @return gint
#' @export
gdkPixbufAnimationGetWidth <- function(animation) {
  .Call("R_gdk_pixbuf_animation_get_width", animation)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationIsStaticImage
#'
#' @param animation PixbufAnimation
#' @return gboolean
#' @export
gdkPixbufAnimationIsStaticImage <- function(animation) {
  .Call("R_gdk_pixbuf_animation_is_static_image", animation)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationIterAdvance
#'
#' @param iter PixbufAnimationIter
#' @param current_time GLib.TimeVal
#' @return gboolean
#' @export
gdkPixbufAnimationIterAdvance <- function(iter, current_time) {
  .Call("R_gdk_pixbuf_animation_iter_advance", iter, current_time)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationIterGetDelayTime
#'
#' @param iter PixbufAnimationIter
#' @return gint
#' @export
gdkPixbufAnimationIterGetDelayTime <- function(iter) {
  .Call("R_gdk_pixbuf_animation_iter_get_delay_time", iter)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationIterGetPixbuf
#'
#' @param iter PixbufAnimationIter
#' @return Pixbuf
#' @export
gdkPixbufAnimationIterGetPixbuf <- function(iter) {
  .Call("R_gdk_pixbuf_animation_iter_get_pixbuf", iter)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufAnimationIterOnCurrentlyLoadingFrame
#'
#' @param iter PixbufAnimationIter
#' @return gboolean
#' @export
gdkPixbufAnimationIterOnCurrentlyLoadingFrame <- function(iter) {
  .Call("R_gdk_pixbuf_animation_iter_on_currently_loading_frame", iter)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufErrorQuark
#'
#' @return GLib.Quark
#' @export
gdkPixbufErrorQuark <- function() {
  .Call("R_gdk_pixbuf_error_quark")$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatCopy
#'
#' @param format PixbufFormat
#' @return PixbufFormat
#' @export
gdkPixbufFormatCopy <- function(format) {
  .Call("R_gdk_pixbuf_format_copy", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatFree
#'
#' @param format PixbufFormat
#' @return Return value from C function
#' @export
gdkPixbufFormatFree <- function(format) {
  invisible(.Call("R_gdk_pixbuf_format_free", format))
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatGetDescription
#'
#' @param format PixbufFormat
#' @return utf8
#' @export
gdkPixbufFormatGetDescription <- function(format) {
  .Call("R_gdk_pixbuf_format_get_description", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatGetExtensions
#'
#' @param format PixbufFormat
#' @return utf8
#' @export
gdkPixbufFormatGetExtensions <- function(format) {
  .Call("R_gdk_pixbuf_format_get_extensions", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatGetLicense
#'
#' @param format PixbufFormat
#' @return utf8
#' @export
gdkPixbufFormatGetLicense <- function(format) {
  .Call("R_gdk_pixbuf_format_get_license", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatGetMimeTypes
#'
#' @param format PixbufFormat
#' @return utf8
#' @export
gdkPixbufFormatGetMimeTypes <- function(format) {
  .Call("R_gdk_pixbuf_format_get_mime_types", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatGetName
#'
#' @param format PixbufFormat
#' @return utf8
#' @export
gdkPixbufFormatGetName <- function(format) {
  .Call("R_gdk_pixbuf_format_get_name", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatIsDisabled
#'
#' @param format PixbufFormat
#' @return gboolean
#' @export
gdkPixbufFormatIsDisabled <- function(format) {
  .Call("R_gdk_pixbuf_format_is_disabled", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatIsSaveOptionSupported
#'
#' @param format PixbufFormat
#' @param option_key utf8
#' @return gboolean
#' @export
gdkPixbufFormatIsSaveOptionSupported <- function(format, option_key) {
  .Call("R_gdk_pixbuf_format_is_save_option_supported", format, option_key)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatIsScalable
#'
#' @param format PixbufFormat
#' @return gboolean
#' @export
gdkPixbufFormatIsScalable <- function(format) {
  .Call("R_gdk_pixbuf_format_is_scalable", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatIsWritable
#'
#' @param format PixbufFormat
#' @return gboolean
#' @export
gdkPixbufFormatIsWritable <- function(format) {
  .Call("R_gdk_pixbuf_format_is_writable", format)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufFormatSetDisabled
#'
#' @param format PixbufFormat
#' @param disabled gboolean
#' @return Return value from C function
#' @export
gdkPixbufFormatSetDisabled <- function(format, disabled) {
  invisible(.Call("R_gdk_pixbuf_format_set_disabled", format, disabled))
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderNew
#'
#' @return PixbufLoader
#' @export
gdkPixbufLoaderNew <- function() {
  .Call("R_gdk_pixbuf_loader_new")$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderNewWithMimeType
#'
#' @param mime_type utf8
#' @return PixbufLoader
#' @export
gdkPixbufLoaderNewWithMimeType <- function(mime_type) {
  .Call("R_gdk_pixbuf_loader_new_with_mime_type", mime_type)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderNewWithType
#'
#' @param image_type utf8
#' @return PixbufLoader
#' @export
gdkPixbufLoaderNewWithType <- function(image_type) {
  .Call("R_gdk_pixbuf_loader_new_with_type", image_type)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderClose
#'
#' @param loader PixbufLoader
#' @return gboolean
#' @export
gdkPixbufLoaderClose <- function(loader) {
  .Call("R_gdk_pixbuf_loader_close", loader)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderGetAnimation
#'
#' @param loader PixbufLoader
#' @return PixbufAnimation
#' @export
gdkPixbufLoaderGetAnimation <- function(loader) {
  .Call("R_gdk_pixbuf_loader_get_animation", loader)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderGetFormat
#'
#' @param loader PixbufLoader
#' @return PixbufFormat
#' @export
gdkPixbufLoaderGetFormat <- function(loader) {
  .Call("R_gdk_pixbuf_loader_get_format", loader)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderGetPixbuf
#'
#' @param loader PixbufLoader
#' @return Pixbuf
#' @export
gdkPixbufLoaderGetPixbuf <- function(loader) {
  .Call("R_gdk_pixbuf_loader_get_pixbuf", loader)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderSetSize
#'
#' @param loader PixbufLoader
#' @param width gint
#' @param height gint
#' @return Return value from C function
#' @export
gdkPixbufLoaderSetSize <- function(loader, width, height) {
  invisible(.Call("R_gdk_pixbuf_loader_set_size", loader, as.integer(width), as.integer(height)))
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderWrite
#'
#' @param loader PixbufLoader
#' @param buf guint8
#' @param count gsize
#' @return gboolean
#' @export
gdkPixbufLoaderWrite <- function(loader, buf, count) {
  .Call("R_gdk_pixbuf_loader_write", loader, buf, as.integer(count))$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufLoaderWriteBytes
#'
#' @param loader PixbufLoader
#' @param buffer GLib.Bytes
#' @return gboolean
#' @export
gdkPixbufLoaderWriteBytes <- function(loader, buffer) {
  .Call("R_gdk_pixbuf_loader_write_bytes", loader, buffer)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufSimpleAnimNew
#'
#' @param width gint
#' @param height gint
#' @param rate gfloat
#' @return PixbufSimpleAnim
#' @export
gdkPixbufSimpleAnimNew <- function(width, height, rate) {
  .Call("R_gdk_pixbuf_simple_anim_new", as.integer(width), as.integer(height), rate)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufSimpleAnimAddFrame
#'
#' @param animation PixbufSimpleAnim
#' @param pixbuf Pixbuf
#' @return Return value from C function
#' @export
gdkPixbufSimpleAnimAddFrame <- function(animation, pixbuf) {
  invisible(.Call("R_gdk_pixbuf_simple_anim_add_frame", animation, pixbuf))
}


#' @rdname gdk-graphics
#' @title gdkPixbufSimpleAnimGetLoop
#'
#' @param animation PixbufSimpleAnim
#' @return gboolean
#' @export
gdkPixbufSimpleAnimGetLoop <- function(animation) {
  .Call("R_gdk_pixbuf_simple_anim_get_loop", animation)$result
}


#' @rdname gdk-graphics
#' @title gdkPixbufSimpleAnimSetLoop
#'
#' @param animation PixbufSimpleAnim
#' @param loop gboolean
#' @return Return value from C function
#' @export
gdkPixbufSimpleAnimSetLoop <- function(animation, loop) {
  invisible(.Call("R_gdk_pixbuf_simple_anim_set_loop", animation, loop))
}


# Enumerations

# Colorspace
RGB <- 0

# InterpType
NEAREST <- 0
TILES <- 1
BILINEAR <- 2
HYPER <- 3

# PixbufAlphaMode
BILEVEL <- 0
FULL <- 1

# PixbufError
CORRUPT_IMAGE <- 0
INSUFFICIENT_MEMORY <- 1
BAD_OPTION <- 2
UNKNOWN_TYPE <- 3
UNSUPPORTED_OPERATION <- 4
FAILED <- 5
INCOMPLETE_ANIMATION <- 6

# PixbufFormatFlags
WRITABLE <- 1
SCALABLE <- 2
THREADSAFE <- 4

# PixbufRotation
NONE <- 0
COUNTERCLOCKWISE <- 90
UPSIDEDOWN <- 180
CLOCKWISE <- 270
