# Autogenerated R wrappers

#' @rdname glib-other
#' @title gBindingGetFlags
#'
#' @param binding Binding
#' @return BindingFlags
#' @export
gBindingGetFlags <- function(binding) {
  .Call("R_g_binding_get_flags", binding)$result
}


#' @rdname glib-other
#' @title gBindingGetSource
#'
#' @param binding Binding
#' @return Object
#' @export
gBindingGetSource <- function(binding) {
  .Call("R_g_binding_get_source", binding)$result
}


#' @rdname glib-other
#' @title gBindingGetSourceProperty
#'
#' @param binding Binding
#' @return utf8
#' @export
gBindingGetSourceProperty <- function(binding) {
  .Call("R_g_binding_get_source_property", binding)$result
}


#' @rdname glib-other
#' @title gBindingGetTarget
#'
#' @param binding Binding
#' @return Object
#' @export
gBindingGetTarget <- function(binding) {
  .Call("R_g_binding_get_target", binding)$result
}


#' @rdname glib-other
#' @title gBindingGetTargetProperty
#'
#' @param binding Binding
#' @return utf8
#' @export
gBindingGetTargetProperty <- function(binding) {
  .Call("R_g_binding_get_target_property", binding)$result
}


#' @rdname glib-other
#' @title gBindingUnbind
#'
#' @param binding Binding
#' @return Return value from C function
#' @export
gBindingUnbind <- function(binding) {
  invisible(.Call("R_g_binding_unbind", binding))
}


#' @rdname glib-other
#' @title gCclosureMarshalBOOLEANBOXEDBOXED
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalBOOLEANBOXEDBOXED <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_BOOLEAN__BOXED_BOXED", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalBOOLEANFLAGS
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalBOOLEANFLAGS <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_BOOLEAN__FLAGS", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalSTRINGOBJECTPOINTER
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalSTRINGOBJECTPOINTER <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_STRING__OBJECT_POINTER", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDBOOLEAN
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDBOOLEAN <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__BOOLEAN", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDBOXED
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDBOXED <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__BOXED", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDCHAR
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDCHAR <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__CHAR", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDDOUBLE
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDDOUBLE <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__DOUBLE", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDENUM
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDENUM <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__ENUM", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDFLAGS
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDFLAGS <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__FLAGS", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDFLOAT
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDFLOAT <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__FLOAT", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDINT
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDINT <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__INT", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDLONG
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDLONG <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__LONG", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDOBJECT
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDOBJECT <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__OBJECT", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDPARAM
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDPARAM <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__PARAM", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDPOINTER
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDPOINTER <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__POINTER", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDSTRING
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDSTRING <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__STRING", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDUCHAR
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDUCHAR <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__UCHAR", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDUINT
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDUINT <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__UINT", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDUINTPOINTER
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDUINTPOINTER <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__UINT_POINTER", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDULONG
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDULONG <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__ULONG", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDVARIANT
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDVARIANT <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__VARIANT", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalVOIDVOID
#'
#' @param closure Closure
#' @param return_value Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalVOIDVOID <- function(closure, return_value, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_VOID__VOID", closure, return_value, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gCclosureMarshalGeneric
#'
#' @param closure Closure
#' @param return_gvalue Value
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @param marshal_data gpointer
#' @return Return value from C function
#' @export
gCclosureMarshalGeneric <- function(closure, return_gvalue, n_param_values, param_values, invocation_hint, marshal_data) {
  invisible(.Call("R_g_cclosure_marshal_generic", closure, return_gvalue, as.integer(n_param_values), param_values, invocation_hint, marshal_data))
}


#' @rdname glib-other
#' @title gClosureNewObject
#'
#' @param sizeof_closure guint
#' @param object Object
#' @return Closure
#' @export
gClosureNewObject <- function(sizeof_closure, object) {
  .Call("R_g_closure_new_object", as.integer(sizeof_closure), object)$result
}


#' @rdname glib-other
#' @title gClosureNewSimple
#'
#' @param sizeof_closure guint
#' @param data gpointer
#' @return Closure
#' @export
gClosureNewSimple <- function(sizeof_closure, data) {
  .Call("R_g_closure_new_simple", as.integer(sizeof_closure), data)$result
}


#' @rdname glib-other
#' @title gClosureInvalidate
#'
#' @param closure Closure
#' @return Return value from C function
#' @export
gClosureInvalidate <- function(closure) {
  invisible(.Call("R_g_closure_invalidate", closure))
}


#' @rdname glib-other
#' @title gClosureInvoke
#'
#' @param closure Closure
#' @param n_param_values guint
#' @param param_values Value
#' @param invocation_hint gpointer
#' @return Return value from C function
#' @export
gClosureInvoke <- function(closure, n_param_values, param_values, invocation_hint) {
  .Call("R_g_closure_invoke", closure, as.integer(n_param_values), param_values, invocation_hint)$return_value
}


#' @rdname glib-other
#' @title gClosureRef
#'
#' @param closure Closure
#' @return Closure
#' @export
gClosureRef <- function(closure) {
  .Call("R_g_closure_ref", closure)$result
}


#' @rdname glib-other
#' @title gClosureSink
#'
#' @param closure Closure
#' @return Return value from C function
#' @export
gClosureSink <- function(closure) {
  invisible(.Call("R_g_closure_sink", closure))
}


#' @rdname glib-other
#' @title gClosureUnref
#'
#' @param closure Closure
#' @return Return value from C function
#' @export
gClosureUnref <- function(closure) {
  invisible(.Call("R_g_closure_unref", closure))
}


#' @rdname gobject-core
#' @title gObjectNewv
#'
#' @param object_type GType
#' @param n_parameters guint
#' @param parameters Parameter
#' @return Object
#' @export
gObjectNewv <- function(object_type, n_parameters, parameters) {
  .Call("R_g_object_newv", object_type, as.integer(n_parameters), parameters)$result
}


#' @rdname gobject-core
#' @title gObjectCompatControl
#'
#' @param what gsize
#' @param data gpointer
#' @return gsize
#' @export
gObjectCompatControl <- function(what, data) {
  .Call("R_g_object_compat_control", as.integer(what), data)$result
}


#' @rdname gobject-core
#' @title gObjectInterfaceFindProperty
#'
#' @param g_iface TypeInterface
#' @param property_name utf8
#' @return ParamSpec
#' @export
gObjectInterfaceFindProperty <- function(g_iface, property_name) {
  .Call("R_g_object_interface_find_property", g_iface, property_name)$result
}


#' @rdname gobject-core
#' @title gObjectInterfaceInstallProperty
#'
#' @param g_iface TypeInterface
#' @param pspec ParamSpec
#' @return Return value from C function
#' @export
gObjectInterfaceInstallProperty <- function(g_iface, pspec) {
  invisible(.Call("R_g_object_interface_install_property", g_iface, pspec))
}


#' @rdname gobject-core
#' @title gObjectInterfaceListProperties
#'
#' @param g_iface TypeInterface
#' @return ParamSpec
#' @export
gObjectInterfaceListProperties <- function(g_iface) {
  .Call("R_g_object_interface_list_properties", g_iface)
}


#' @rdname gobject-core
#' @title gObjectBindProperty
#'
#' @param source Object
#' @param source_property utf8
#' @param target Object
#' @param target_property utf8
#' @param flags BindingFlags
#' @return Binding
#' @export
gObjectBindProperty <- function(source, source_property, target, target_property, flags) {
  .Call("R_g_object_bind_property", source, source_property, target, target_property, flags)$result
}


#' @rdname gobject-core
#' @title gObjectBindPropertyFull
#'
#' @param source Object
#' @param source_property utf8
#' @param target Object
#' @param target_property utf8
#' @param flags BindingFlags
#' @param transform_to function — BindingTransformFunc function(binding, from_value, to_value)
#' @param transform_from function — BindingTransformFunc function(binding, from_value, to_value)
#' @return Binding
#' @export
gObjectBindPropertyFull <- function(source, source_property, target, target_property, flags, transform_to, transform_from) {
  .Call("R_g_object_bind_property_full", source, source_property, target, target_property, flags, transform_to, transform_from)$result
}


#' @rdname gobject-core
#' @title gObjectBindPropertyWithClosures
#'
#' @param source Object
#' @param source_property utf8
#' @param target Object
#' @param target_property utf8
#' @param flags BindingFlags
#' @param transform_to Closure
#' @param transform_from Closure
#' @return Binding
#' @export
gObjectBindPropertyWithClosures <- function(source, source_property, target, target_property, flags, transform_to, transform_from) {
  .Call("R_g_object_bind_property_with_closures", source, source_property, target, target_property, flags, transform_to, transform_from)$result
}


#' @rdname gobject-core
#' @title gObjectForceFloating
#'
#' @param object Object
#' @return Return value from C function
#' @export
gObjectForceFloating <- function(object) {
  invisible(.Call("R_g_object_force_floating", object))
}


#' @rdname gobject-core
#' @title gObjectFreezeNotify
#'
#' @param object Object
#' @return Return value from C function
#' @export
gObjectFreezeNotify <- function(object) {
  invisible(.Call("R_g_object_freeze_notify", object))
}


#' @rdname gobject-core
#' @title gObjectGetData
#'
#' @param object Object
#' @param key utf8
#' @return gpointer
#' @export
gObjectGetData <- function(object, key) {
  .Call("R_g_object_get_data", object, key)$result
}


#' @rdname gobject-core
#' @title gObjectGetProperty
#'
#' @param object Object
#' @param property_name utf8
#' @param value Value
#' @return Return value from C function
#' @export
gObjectGetProperty <- function(object, property_name, value) {
  invisible(.Call("R_g_object_get_property", object, property_name, value))
}


#' @rdname gobject-core
#' @title gObjectGetQdata
#'
#' @param object Object
#' @param quark GLib.Quark
#' @return gpointer
#' @export
gObjectGetQdata <- function(object, quark) {
  .Call("R_g_object_get_qdata", object, quark)$result
}


#' @rdname gobject-core
#' @title gObjectGetv
#'
#' @param object Object
#' @param n_properties guint
#' @param names utf8
#' @param values Value
#' @return Return value from C function
#' @export
gObjectGetv <- function(object, n_properties, names, values) {
  invisible(.Call("R_g_object_getv", object, as.integer(n_properties), names, values))
}


#' @rdname gobject-core
#' @title gObjectIsFloating
#'
#' @param object Object
#' @return gboolean
#' @export
gObjectIsFloating <- function(object) {
  .Call("R_g_object_is_floating", object)$result
}


#' @rdname gobject-core
#' @title gObjectNotify
#'
#' @param object Object
#' @param property_name utf8
#' @return Return value from C function
#' @export
gObjectNotify <- function(object, property_name) {
  invisible(.Call("R_g_object_notify", object, property_name))
}


#' @rdname gobject-core
#' @title gObjectNotifyByPspec
#'
#' @param object Object
#' @param pspec ParamSpec
#' @return Return value from C function
#' @export
gObjectNotifyByPspec <- function(object, pspec) {
  invisible(.Call("R_g_object_notify_by_pspec", object, pspec))
}


#' @rdname gobject-core
#' @title gObjectRef
#'
#' @param object Object
#' @return Object
#' @export
gObjectRef <- function(object) {
  .Call("R_g_object_ref", object)$result
}


#' @rdname gobject-core
#' @title gObjectRefSink
#'
#' @param object Object
#' @return Object
#' @export
gObjectRefSink <- function(object) {
  .Call("R_g_object_ref_sink", object)$result
}


#' @rdname gobject-core
#' @title gObjectRunDispose
#'
#' @param object Object
#' @return Return value from C function
#' @export
gObjectRunDispose <- function(object) {
  invisible(.Call("R_g_object_run_dispose", object))
}


#' @rdname gobject-core
#' @title gObjectSetData
#'
#' @param object Object
#' @param key utf8
#' @param data gpointer
#' @return Return value from C function
#' @export
gObjectSetData <- function(object, key, data) {
  invisible(.Call("R_g_object_set_data", object, key, data))
}


#' @rdname gobject-core
#' @title gObjectSetProperty
#'
#' @param object Object
#' @param property_name utf8
#' @param value Value
#' @return Return value from C function
#' @export
gObjectSetProperty <- function(object, property_name, value) {
  invisible(.Call("R_g_object_set_property", object, property_name, value))
}


#' @rdname gobject-core
#' @title gObjectStealData
#'
#' @param object Object
#' @param key utf8
#' @return gpointer
#' @export
gObjectStealData <- function(object, key) {
  .Call("R_g_object_steal_data", object, key)$result
}


#' @rdname gobject-core
#' @title gObjectStealQdata
#'
#' @param object Object
#' @param quark GLib.Quark
#' @return gpointer
#' @export
gObjectStealQdata <- function(object, quark) {
  .Call("R_g_object_steal_qdata", object, quark)$result
}


#' @rdname gobject-core
#' @title gObjectThawNotify
#'
#' @param object Object
#' @return Return value from C function
#' @export
gObjectThawNotify <- function(object) {
  invisible(.Call("R_g_object_thaw_notify", object))
}


#' @rdname gobject-core
#' @title gObjectUnref
#'
#' @param object Object
#' @return Return value from C function
#' @export
gObjectUnref <- function(object) {
  invisible(.Call("R_g_object_unref", object))
}


#' @rdname gobject-core
#' @title gObjectWatchClosure
#'
#' @param object Object
#' @param closure Closure
#' @return Return value from C function
#' @export
gObjectWatchClosure <- function(object, closure) {
  invisible(.Call("R_g_object_watch_closure", object, closure))
}


#' @rdname gobject-core
#' @title gObjectClassFindProperty
#'
#' @param oclass ObjectClass
#' @param property_name utf8
#' @return ParamSpec
#' @export
gObjectClassFindProperty <- function(oclass, property_name) {
  .Call("R_g_object_class_find_property", oclass, property_name)$result
}


#' @rdname gobject-core
#' @title gObjectClassInstallProperties
#'
#' @param oclass ObjectClass
#' @param n_pspecs guint
#' @param pspecs ParamSpec
#' @return Return value from C function
#' @export
gObjectClassInstallProperties <- function(oclass, n_pspecs, pspecs) {
  invisible(.Call("R_g_object_class_install_properties", oclass, as.integer(n_pspecs), pspecs))
}


#' @rdname gobject-core
#' @title gObjectClassInstallProperty
#'
#' @param oclass ObjectClass
#' @param property_id guint
#' @param pspec ParamSpec
#' @return Return value from C function
#' @export
gObjectClassInstallProperty <- function(oclass, property_id, pspec) {
  invisible(.Call("R_g_object_class_install_property", oclass, as.integer(property_id), pspec))
}


#' @rdname gobject-core
#' @title gObjectClassListProperties
#'
#' @param oclass ObjectClass
#' @return ParamSpec
#' @export
gObjectClassListProperties <- function(oclass) {
  .Call("R_g_object_class_list_properties", oclass)
}


#' @rdname gobject-core
#' @title gObjectClassOverrideProperty
#'
#' @param oclass ObjectClass
#' @param property_id guint
#' @param name utf8
#' @return Return value from C function
#' @export
gObjectClassOverrideProperty <- function(oclass, property_id, name) {
  invisible(.Call("R_g_object_class_override_property", oclass, as.integer(property_id), name))
}


#' @rdname glib-other
#' @title gParamSpecGetBlurb
#'
#' @param pspec ParamSpec
#' @return utf8
#' @export
gParamSpecGetBlurb <- function(pspec) {
  .Call("R_g_param_spec_get_blurb", pspec)$result
}


#' @rdname glib-other
#' @title gParamSpecGetDefaultValue
#'
#' @param pspec ParamSpec
#' @return Value
#' @export
gParamSpecGetDefaultValue <- function(pspec) {
  .Call("R_g_param_spec_get_default_value", pspec)$result
}


#' @rdname glib-other
#' @title gParamSpecGetName
#'
#' @param pspec ParamSpec
#' @return utf8
#' @export
gParamSpecGetName <- function(pspec) {
  .Call("R_g_param_spec_get_name", pspec)$result
}


#' @rdname glib-other
#' @title gParamSpecGetNameQuark
#'
#' @param pspec ParamSpec
#' @return GLib.Quark
#' @export
gParamSpecGetNameQuark <- function(pspec) {
  .Call("R_g_param_spec_get_name_quark", pspec)$result
}


#' @rdname glib-other
#' @title gParamSpecGetNick
#'
#' @param pspec ParamSpec
#' @return utf8
#' @export
gParamSpecGetNick <- function(pspec) {
  .Call("R_g_param_spec_get_nick", pspec)$result
}


#' @rdname glib-other
#' @title gParamSpecGetQdata
#'
#' @param pspec ParamSpec
#' @param quark GLib.Quark
#' @return gpointer
#' @export
gParamSpecGetQdata <- function(pspec, quark) {
  .Call("R_g_param_spec_get_qdata", pspec, quark)$result
}


#' @rdname glib-other
#' @title gParamSpecGetRedirectTarget
#'
#' @param pspec ParamSpec
#' @return ParamSpec
#' @export
gParamSpecGetRedirectTarget <- function(pspec) {
  .Call("R_g_param_spec_get_redirect_target", pspec)$result
}


#' @rdname glib-other
#' @title gParamSpecSetQdata
#'
#' @param pspec ParamSpec
#' @param quark GLib.Quark
#' @param data gpointer
#' @return Return value from C function
#' @export
gParamSpecSetQdata <- function(pspec, quark, data) {
  invisible(.Call("R_g_param_spec_set_qdata", pspec, quark, data))
}


#' @rdname glib-other
#' @title gParamSpecSink
#'
#' @param pspec ParamSpec
#' @return Return value from C function
#' @export
gParamSpecSink <- function(pspec) {
  invisible(.Call("R_g_param_spec_sink", pspec))
}


#' @rdname glib-other
#' @title gParamSpecStealQdata
#'
#' @param pspec ParamSpec
#' @param quark GLib.Quark
#' @return gpointer
#' @export
gParamSpecStealQdata <- function(pspec, quark) {
  .Call("R_g_param_spec_steal_qdata", pspec, quark)$result
}


#' @rdname glib-other
#' @title gParamSpecPoolInsert
#'
#' @param pool ParamSpecPool
#' @param pspec ParamSpec
#' @param owner_type GType
#' @return Return value from C function
#' @export
gParamSpecPoolInsert <- function(pool, pspec, owner_type) {
  invisible(.Call("R_g_param_spec_pool_insert", pool, pspec, owner_type))
}


#' @rdname glib-other
#' @title gParamSpecPoolList
#'
#' @param pool ParamSpecPool
#' @param owner_type GType
#' @return ParamSpec
#' @export
gParamSpecPoolList <- function(pool, owner_type) {
  .Call("R_g_param_spec_pool_list", pool, owner_type)
}


#' @rdname glib-other
#' @title gParamSpecPoolListOwned
#'
#' @param pool ParamSpecPool
#' @param owner_type GType
#' @return GLib.List
#' @export
gParamSpecPoolListOwned <- function(pool, owner_type) {
  .Call("R_g_param_spec_pool_list_owned", pool, owner_type)$result
}


#' @rdname glib-other
#' @title gParamSpecPoolLookup
#'
#' @param pool ParamSpecPool
#' @param param_name utf8
#' @param owner_type GType
#' @param walk_ancestors gboolean
#' @return ParamSpec
#' @export
gParamSpecPoolLookup <- function(pool, param_name, owner_type, walk_ancestors) {
  .Call("R_g_param_spec_pool_lookup", pool, param_name, owner_type, walk_ancestors)$result
}


#' @rdname glib-other
#' @title gParamSpecPoolRemove
#'
#' @param pool ParamSpecPool
#' @param pspec ParamSpec
#' @return Return value from C function
#' @export
gParamSpecPoolRemove <- function(pool, pspec) {
  invisible(.Call("R_g_param_spec_pool_remove", pool, pspec))
}


#' @rdname glib-mainloop
#' @title gSourceSetClosure
#'
#' @param source GLib.Source
#' @param closure Closure
#' @return Return value from C function
#' @export
gSourceSetClosure <- function(source, closure) {
  invisible(.Call("R_g_source_set_closure", source, closure))
}


#' @rdname glib-mainloop
#' @title gSourceSetDummyCallback
#'
#' @param source GLib.Source
#' @return Return value from C function
#' @export
gSourceSetDummyCallback <- function(source) {
  invisible(.Call("R_g_source_set_dummy_callback", source))
}


#' @rdname glib-other
#' @title gTypeClassAddPrivate
#'
#' @param g_class TypeClass
#' @param private_size gsize
#' @return Return value from C function
#' @export
gTypeClassAddPrivate <- function(g_class, private_size) {
  invisible(.Call("R_g_type_class_add_private", g_class, as.integer(private_size)))
}


#' @rdname glib-other
#' @title gTypeClassGetPrivate
#'
#' @param klass TypeClass
#' @param private_type GType
#' @return gpointer
#' @export
gTypeClassGetPrivate <- function(klass, private_type) {
  .Call("R_g_type_class_get_private", klass, private_type)$result
}


#' @rdname glib-other
#' @title gTypeClassPeekParent
#'
#' @param g_class TypeClass
#' @return TypeClass
#' @export
gTypeClassPeekParent <- function(g_class) {
  .Call("R_g_type_class_peek_parent", g_class)$result
}


#' @rdname glib-other
#' @title gTypeClassUnref
#'
#' @param g_class TypeClass
#' @return Return value from C function
#' @export
gTypeClassUnref <- function(g_class) {
  invisible(.Call("R_g_type_class_unref", g_class))
}


#' @rdname glib-other
#' @title gTypeClassAdjustPrivateOffset
#'
#' @param g_class gpointer
#' @param private_size_or_offset gint
#' @return Return value from C function
#' @export
gTypeClassAdjustPrivateOffset <- function(g_class, private_size_or_offset) {
  invisible(.Call("R_g_type_class_adjust_private_offset", g_class, private_size_or_offset))
}


#' @rdname glib-other
#' @title gTypeClassPeek
#'
#' @param type GType
#' @return TypeClass
#' @export
gTypeClassPeek <- function(type) {
  .Call("R_g_type_class_peek", type)$result
}


#' @rdname glib-other
#' @title gTypeClassPeekStatic
#'
#' @param type GType
#' @return TypeClass
#' @export
gTypeClassPeekStatic <- function(type) {
  .Call("R_g_type_class_peek_static", type)$result
}


#' @rdname glib-other
#' @title gTypeClassRef
#'
#' @param type GType
#' @return TypeClass
#' @export
gTypeClassRef <- function(type) {
  .Call("R_g_type_class_ref", type)$result
}


#' @rdname glib-other
#' @title gTypeInstanceGetPrivate
#'
#' @param instance TypeInstance
#' @param private_type GType
#' @return gpointer
#' @export
gTypeInstanceGetPrivate <- function(instance, private_type) {
  .Call("R_g_type_instance_get_private", instance, private_type)$result
}


#' @rdname glib-other
#' @title gTypeInterfacePeekParent
#'
#' @param g_iface TypeInterface
#' @return TypeInterface
#' @export
gTypeInterfacePeekParent <- function(g_iface) {
  .Call("R_g_type_interface_peek_parent", g_iface)$result
}


#' @rdname glib-other
#' @title gTypeInterfaceAddPrerequisite
#'
#' @param interface_type GType
#' @param prerequisite_type GType
#' @return Return value from C function
#' @export
gTypeInterfaceAddPrerequisite <- function(interface_type, prerequisite_type) {
  invisible(.Call("R_g_type_interface_add_prerequisite", interface_type, prerequisite_type))
}


#' @rdname glib-other
#' @title gTypeInterfaceGetPlugin
#'
#' @param instance_type GType
#' @param interface_type GType
#' @return TypePlugin
#' @export
gTypeInterfaceGetPlugin <- function(instance_type, interface_type) {
  .Call("R_g_type_interface_get_plugin", instance_type, interface_type)$result
}


#' @rdname glib-other
#' @title gTypeInterfacePeek
#'
#' @param instance_class TypeClass
#' @param iface_type GType
#' @return TypeInterface
#' @export
gTypeInterfacePeek <- function(instance_class, iface_type) {
  .Call("R_g_type_interface_peek", instance_class, iface_type)$result
}


#' @rdname glib-other
#' @title gTypeInterfacePrerequisites
#'
#' @param interface_type GType
#' @return GType
#' @export
gTypeInterfacePrerequisites <- function(interface_type) {
  .Call("R_g_type_interface_prerequisites", interface_type)
}


#' @rdname glib-other
#' @title gTypeModuleAddInterface
#'
#' @param module TypeModule
#' @param instance_type GType
#' @param interface_type GType
#' @param interface_info InterfaceInfo
#' @return Return value from C function
#' @export
gTypeModuleAddInterface <- function(module, instance_type, interface_type, interface_info) {
  invisible(.Call("R_g_type_module_add_interface", module, instance_type, interface_type, interface_info))
}


#' @rdname glib-other
#' @title gTypeModuleRegisterEnum
#'
#' @param module TypeModule
#' @param name utf8
#' @param const_static_values EnumValue
#' @return GType
#' @export
gTypeModuleRegisterEnum <- function(module, name, const_static_values) {
  .Call("R_g_type_module_register_enum", module, name, const_static_values)$result
}


#' @rdname glib-other
#' @title gTypeModuleRegisterFlags
#'
#' @param module TypeModule
#' @param name utf8
#' @param const_static_values FlagsValue
#' @return GType
#' @export
gTypeModuleRegisterFlags <- function(module, name, const_static_values) {
  .Call("R_g_type_module_register_flags", module, name, const_static_values)$result
}


#' @rdname glib-other
#' @title gTypeModuleRegisterType
#'
#' @param module TypeModule
#' @param parent_type GType
#' @param type_name utf8
#' @param type_info TypeInfo
#' @param flags TypeFlags
#' @return GType
#' @export
gTypeModuleRegisterType <- function(module, parent_type, type_name, type_info, flags) {
  .Call("R_g_type_module_register_type", module, parent_type, type_name, type_info, flags)$result
}


#' @rdname glib-other
#' @title gTypeModuleSetName
#'
#' @param module TypeModule
#' @param name utf8
#' @return Return value from C function
#' @export
gTypeModuleSetName <- function(module, name) {
  invisible(.Call("R_g_type_module_set_name", module, name))
}


#' @rdname glib-other
#' @title gTypeModuleUnuse
#'
#' @param module TypeModule
#' @return Return value from C function
#' @export
gTypeModuleUnuse <- function(module) {
  invisible(.Call("R_g_type_module_unuse", module))
}


#' @rdname glib-other
#' @title gTypeModuleUse
#'
#' @param module TypeModule
#' @return gboolean
#' @export
gTypeModuleUse <- function(module) {
  .Call("R_g_type_module_use", module)$result
}


#' @rdname glib-other
#' @title gTypePluginCompleteInterfaceInfo
#'
#' @param plugin TypePlugin
#' @param instance_type GType
#' @param interface_type GType
#' @param info InterfaceInfo
#' @return Return value from C function
#' @export
gTypePluginCompleteInterfaceInfo <- function(plugin, instance_type, interface_type, info) {
  invisible(.Call("R_g_type_plugin_complete_interface_info", plugin, instance_type, interface_type, info))
}


#' @rdname glib-other
#' @title gTypePluginCompleteTypeInfo
#'
#' @param plugin TypePlugin
#' @param g_type GType
#' @param info TypeInfo
#' @param value_table TypeValueTable
#' @return Return value from C function
#' @export
gTypePluginCompleteTypeInfo <- function(plugin, g_type, info, value_table) {
  invisible(.Call("R_g_type_plugin_complete_type_info", plugin, g_type, info, value_table))
}


#' @rdname glib-other
#' @title gTypePluginUnuse
#'
#' @param plugin TypePlugin
#' @return Return value from C function
#' @export
gTypePluginUnuse <- function(plugin) {
  invisible(.Call("R_g_type_plugin_unuse", plugin))
}


#' @rdname glib-other
#' @title gTypePluginUse
#'
#' @param plugin TypePlugin
#' @return Return value from C function
#' @export
gTypePluginUse <- function(plugin) {
  invisible(.Call("R_g_type_plugin_use", plugin))
}


#' @rdname glib-other
#' @title gValueCopy
#'
#' @param src_value Value
#' @param dest_value Value
#' @return Return value from C function
#' @export
gValueCopy <- function(src_value, dest_value) {
  invisible(.Call("R_g_value_copy", src_value, dest_value))
}


#' @rdname glib-other
#' @title gValueDupObject
#'
#' @param value Value
#' @return Object
#' @export
gValueDupObject <- function(value) {
  .Call("R_g_value_dup_object", value)$result
}


#' @rdname glib-other
#' @title gValueDupString
#'
#' @param value Value
#' @return utf8
#' @export
gValueDupString <- function(value) {
  .Call("R_g_value_dup_string", value)$result
}


#' @rdname glib-other
#' @title gValueDupVariant
#'
#' @param value Value
#' @return GLib.Variant
#' @export
gValueDupVariant <- function(value) {
  .Call("R_g_value_dup_variant", value)$result
}


#' @rdname glib-other
#' @title gValueFitsPointer
#'
#' @param value Value
#' @return gboolean
#' @export
gValueFitsPointer <- function(value) {
  .Call("R_g_value_fits_pointer", value)$result
}


#' @rdname glib-other
#' @title gValueGetBoolean
#'
#' @param value Value
#' @return gboolean
#' @export
gValueGetBoolean <- function(value) {
  .Call("R_g_value_get_boolean", value)$result
}


#' @rdname glib-other
#' @title gValueGetBoxed
#'
#' @param value Value
#' @return gpointer
#' @export
gValueGetBoxed <- function(value) {
  .Call("R_g_value_get_boxed", value)$result
}


#' @rdname glib-other
#' @title gValueGetChar
#'
#' @param value Value
#' @return gchar
#' @export
gValueGetChar <- function(value) {
  .Call("R_g_value_get_char", value)$result
}


#' @rdname glib-other
#' @title gValueGetDouble
#'
#' @param value Value
#' @return gdouble
#' @export
gValueGetDouble <- function(value) {
  .Call("R_g_value_get_double", value)$result
}


#' @rdname glib-other
#' @title gValueGetEnum
#'
#' @param value Value
#' @return gint
#' @export
gValueGetEnum <- function(value) {
  .Call("R_g_value_get_enum", value)$result
}


#' @rdname glib-other
#' @title gValueGetFlags
#'
#' @param value Value
#' @return guint
#' @export
gValueGetFlags <- function(value) {
  .Call("R_g_value_get_flags", value)$result
}


#' @rdname glib-other
#' @title gValueGetFloat
#'
#' @param value Value
#' @return gfloat
#' @export
gValueGetFloat <- function(value) {
  .Call("R_g_value_get_float", value)$result
}


#' @rdname glib-other
#' @title gValueGetGtype
#'
#' @param value Value
#' @return GType
#' @export
gValueGetGtype <- function(value) {
  .Call("R_g_value_get_gtype", value)$result
}


#' @rdname glib-other
#' @title gValueGetInt
#'
#' @param value Value
#' @return gint
#' @export
gValueGetInt <- function(value) {
  .Call("R_g_value_get_int", value)$result
}


#' @rdname glib-other
#' @title gValueGetInt64
#'
#' @param value Value
#' @return gint64
#' @export
gValueGetInt64 <- function(value) {
  .Call("R_g_value_get_int64", value)$result
}


#' @rdname glib-other
#' @title gValueGetLong
#'
#' @param value Value
#' @return glong
#' @export
gValueGetLong <- function(value) {
  .Call("R_g_value_get_long", value)$result
}


#' @rdname glib-other
#' @title gValueGetObject
#'
#' @param value Value
#' @return Object
#' @export
gValueGetObject <- function(value) {
  .Call("R_g_value_get_object", value)$result
}


#' @rdname glib-other
#' @title gValueGetParam
#'
#' @param value Value
#' @return ParamSpec
#' @export
gValueGetParam <- function(value) {
  .Call("R_g_value_get_param", value)$result
}


#' @rdname glib-other
#' @title gValueGetPointer
#'
#' @param value Value
#' @return gpointer
#' @export
gValueGetPointer <- function(value) {
  .Call("R_g_value_get_pointer", value)$result
}


#' @rdname glib-other
#' @title gValueGetSchar
#'
#' @param value Value
#' @return gint8
#' @export
gValueGetSchar <- function(value) {
  .Call("R_g_value_get_schar", value)$result
}


#' @rdname glib-other
#' @title gValueGetString
#'
#' @param value Value
#' @return utf8
#' @export
gValueGetString <- function(value) {
  .Call("R_g_value_get_string", value)$result
}


#' @rdname glib-other
#' @title gValueGetUchar
#'
#' @param value Value
#' @return guint8
#' @export
gValueGetUchar <- function(value) {
  .Call("R_g_value_get_uchar", value)$result
}


#' @rdname glib-other
#' @title gValueGetUint
#'
#' @param value Value
#' @return guint
#' @export
gValueGetUint <- function(value) {
  .Call("R_g_value_get_uint", value)$result
}


#' @rdname glib-other
#' @title gValueGetUint64
#'
#' @param value Value
#' @return guint64
#' @export
gValueGetUint64 <- function(value) {
  .Call("R_g_value_get_uint64", value)$result
}


#' @rdname glib-other
#' @title gValueGetUlong
#'
#' @param value Value
#' @return gulong
#' @export
gValueGetUlong <- function(value) {
  .Call("R_g_value_get_ulong", value)$result
}


#' @rdname glib-other
#' @title gValueGetVariant
#'
#' @param value Value
#' @return GLib.Variant
#' @export
gValueGetVariant <- function(value) {
  .Call("R_g_value_get_variant", value)$result
}


#' @rdname glib-other
#' @title gValueInit
#'
#' @param value Value
#' @param g_type GType
#' @return Value
#' @export
gValueInit <- function(value, g_type) {
  .Call("R_g_value_init", value, g_type)$result
}


#' @rdname glib-other
#' @title gValueInitFromInstance
#'
#' @param value Value
#' @param instance TypeInstance
#' @return Return value from C function
#' @export
gValueInitFromInstance <- function(value, instance) {
  invisible(.Call("R_g_value_init_from_instance", value, instance))
}


#' @rdname glib-other
#' @title gValuePeekPointer
#'
#' @param value Value
#' @return gpointer
#' @export
gValuePeekPointer <- function(value) {
  .Call("R_g_value_peek_pointer", value)$result
}


#' @rdname glib-other
#' @title gValueReset
#'
#' @param value Value
#' @return Value
#' @export
gValueReset <- function(value) {
  .Call("R_g_value_reset", value)$result
}


#' @rdname glib-other
#' @title gValueSetBoolean
#'
#' @param value Value
#' @param v_boolean gboolean
#' @return Return value from C function
#' @export
gValueSetBoolean <- function(value, v_boolean) {
  invisible(.Call("R_g_value_set_boolean", value, v_boolean))
}


#' @rdname glib-other
#' @title gValueSetBoxed
#'
#' @param value Value
#' @param v_boxed gpointer
#' @return Return value from C function
#' @export
gValueSetBoxed <- function(value, v_boxed) {
  invisible(.Call("R_g_value_set_boxed", value, v_boxed))
}


#' @rdname glib-other
#' @title gValueSetBoxedTakeOwnership
#'
#' @param value Value
#' @param v_boxed gpointer
#' @return Return value from C function
#' @export
gValueSetBoxedTakeOwnership <- function(value, v_boxed) {
  invisible(.Call("R_g_value_set_boxed_take_ownership", value, v_boxed))
}


#' @rdname glib-other
#' @title gValueSetChar
#'
#' @param value Value
#' @param v_char gchar
#' @return Return value from C function
#' @export
gValueSetChar <- function(value, v_char) {
  invisible(.Call("R_g_value_set_char", value, v_char))
}


#' @rdname glib-other
#' @title gValueSetDouble
#'
#' @param value Value
#' @param v_double gdouble
#' @return Return value from C function
#' @export
gValueSetDouble <- function(value, v_double) {
  invisible(.Call("R_g_value_set_double", value, v_double))
}


#' @rdname glib-other
#' @title gValueSetEnum
#'
#' @param value Value
#' @param v_enum gint
#' @return Return value from C function
#' @export
gValueSetEnum <- function(value, v_enum) {
  invisible(.Call("R_g_value_set_enum", value, as.integer(v_enum)))
}


#' @rdname glib-other
#' @title gValueSetFlags
#'
#' @param value Value
#' @param v_flags guint
#' @return Return value from C function
#' @export
gValueSetFlags <- function(value, v_flags) {
  invisible(.Call("R_g_value_set_flags", value, as.integer(v_flags)))
}


#' @rdname glib-other
#' @title gValueSetFloat
#'
#' @param value Value
#' @param v_float gfloat
#' @return Return value from C function
#' @export
gValueSetFloat <- function(value, v_float) {
  invisible(.Call("R_g_value_set_float", value, v_float))
}


#' @rdname glib-other
#' @title gValueSetGtype
#'
#' @param value Value
#' @param v_gtype GType
#' @return Return value from C function
#' @export
gValueSetGtype <- function(value, v_gtype) {
  invisible(.Call("R_g_value_set_gtype", value, v_gtype))
}


#' @rdname glib-other
#' @title gValueSetInstance
#'
#' @param value Value
#' @param instance gpointer
#' @return Return value from C function
#' @export
gValueSetInstance <- function(value, instance) {
  invisible(.Call("R_g_value_set_instance", value, instance))
}


#' @rdname glib-other
#' @title gValueSetInt
#'
#' @param value Value
#' @param v_int gint
#' @return Return value from C function
#' @export
gValueSetInt <- function(value, v_int) {
  invisible(.Call("R_g_value_set_int", value, as.integer(v_int)))
}


#' @rdname glib-other
#' @title gValueSetInt64
#'
#' @param value Value
#' @param v_int64 gint64
#' @return Return value from C function
#' @export
gValueSetInt64 <- function(value, v_int64) {
  invisible(.Call("R_g_value_set_int64", value, v_int64))
}


#' @rdname glib-other
#' @title gValueSetLong
#'
#' @param value Value
#' @param v_long glong
#' @return Return value from C function
#' @export
gValueSetLong <- function(value, v_long) {
  invisible(.Call("R_g_value_set_long", value, v_long))
}


#' @rdname glib-other
#' @title gValueSetObject
#'
#' @param value Value
#' @param v_object Object
#' @return Return value from C function
#' @export
gValueSetObject <- function(value, v_object) {
  invisible(.Call("R_g_value_set_object", value, v_object))
}


#' @rdname glib-other
#' @title gValueSetParam
#'
#' @param value Value
#' @param param ParamSpec
#' @return Return value from C function
#' @export
gValueSetParam <- function(value, param) {
  invisible(.Call("R_g_value_set_param", value, param))
}


#' @rdname glib-other
#' @title gValueSetPointer
#'
#' @param value Value
#' @param v_pointer gpointer
#' @return Return value from C function
#' @export
gValueSetPointer <- function(value, v_pointer) {
  invisible(.Call("R_g_value_set_pointer", value, v_pointer))
}


#' @rdname glib-other
#' @title gValueSetSchar
#'
#' @param value Value
#' @param v_char gint8
#' @return Return value from C function
#' @export
gValueSetSchar <- function(value, v_char) {
  invisible(.Call("R_g_value_set_schar", value, as.integer(v_char)))
}


#' @rdname glib-other
#' @title gValueSetStaticBoxed
#'
#' @param value Value
#' @param v_boxed gpointer
#' @return Return value from C function
#' @export
gValueSetStaticBoxed <- function(value, v_boxed) {
  invisible(.Call("R_g_value_set_static_boxed", value, v_boxed))
}


#' @rdname glib-other
#' @title gValueSetStaticString
#'
#' @param value Value
#' @param v_string utf8
#' @return Return value from C function
#' @export
gValueSetStaticString <- function(value, v_string) {
  invisible(.Call("R_g_value_set_static_string", value, v_string))
}


#' @rdname glib-other
#' @title gValueSetString
#'
#' @param value Value
#' @param v_string utf8
#' @return Return value from C function
#' @export
gValueSetString <- function(value, v_string) {
  invisible(.Call("R_g_value_set_string", value, v_string))
}


#' @rdname glib-other
#' @title gValueSetStringTakeOwnership
#'
#' @param value Value
#' @param v_string utf8
#' @return Return value from C function
#' @export
gValueSetStringTakeOwnership <- function(value, v_string) {
  invisible(.Call("R_g_value_set_string_take_ownership", value, v_string))
}


#' @rdname glib-other
#' @title gValueSetUchar
#'
#' @param value Value
#' @param v_uchar guint8
#' @return Return value from C function
#' @export
gValueSetUchar <- function(value, v_uchar) {
  invisible(.Call("R_g_value_set_uchar", value, as.integer(v_uchar)))
}


#' @rdname glib-other
#' @title gValueSetUint
#'
#' @param value Value
#' @param v_uint guint
#' @return Return value from C function
#' @export
gValueSetUint <- function(value, v_uint) {
  invisible(.Call("R_g_value_set_uint", value, as.integer(v_uint)))
}


#' @rdname glib-other
#' @title gValueSetUint64
#'
#' @param value Value
#' @param v_uint64 guint64
#' @return Return value from C function
#' @export
gValueSetUint64 <- function(value, v_uint64) {
  invisible(.Call("R_g_value_set_uint64", value, as.integer(v_uint64)))
}


#' @rdname glib-other
#' @title gValueSetUlong
#'
#' @param value Value
#' @param v_ulong gulong
#' @return Return value from C function
#' @export
gValueSetUlong <- function(value, v_ulong) {
  invisible(.Call("R_g_value_set_ulong", value, as.integer(v_ulong)))
}


#' @rdname glib-other
#' @title gValueSetVariant
#'
#' @param value Value
#' @param variant GLib.Variant
#' @return Return value from C function
#' @export
gValueSetVariant <- function(value, variant) {
  invisible(.Call("R_g_value_set_variant", value, variant))
}


#' @rdname glib-other
#' @title gValueTakeBoxed
#'
#' @param value Value
#' @param v_boxed gpointer
#' @return Return value from C function
#' @export
gValueTakeBoxed <- function(value, v_boxed) {
  invisible(.Call("R_g_value_take_boxed", value, v_boxed))
}


#' @rdname glib-other
#' @title gValueTakeString
#'
#' @param value Value
#' @param v_string utf8
#' @return Return value from C function
#' @export
gValueTakeString <- function(value, v_string) {
  invisible(.Call("R_g_value_take_string", value, v_string))
}


#' @rdname glib-other
#' @title gValueTakeVariant
#'
#' @param value Value
#' @param variant GLib.Variant
#' @return Return value from C function
#' @export
gValueTakeVariant <- function(value, variant) {
  invisible(.Call("R_g_value_take_variant", value, variant))
}


#' @rdname glib-other
#' @title gValueTransform
#'
#' @param src_value Value
#' @param dest_value Value
#' @return gboolean
#' @export
gValueTransform <- function(src_value, dest_value) {
  .Call("R_g_value_transform", src_value, dest_value)$result
}


#' @rdname glib-other
#' @title gValueUnset
#'
#' @param value Value
#' @return Return value from C function
#' @export
gValueUnset <- function(value) {
  invisible(.Call("R_g_value_unset", value))
}


#' @rdname glib-other
#' @title gValueTypeCompatible
#'
#' @param src_type GType
#' @param dest_type GType
#' @return gboolean
#' @export
gValueTypeCompatible <- function(src_type, dest_type) {
  .Call("R_g_value_type_compatible", src_type, dest_type)$result
}


#' @rdname glib-other
#' @title gValueTypeTransformable
#'
#' @param src_type GType
#' @param dest_type GType
#' @return gboolean
#' @export
gValueTypeTransformable <- function(src_type, dest_type) {
  .Call("R_g_value_type_transformable", src_type, dest_type)$result
}


#' @rdname glib-other
#' @title gValueArrayNew
#'
#' @param n_prealloced guint
#' @return ValueArray
#' @export
gValueArrayNew <- function(n_prealloced) {
  .Call("R_g_value_array_new", as.integer(n_prealloced))$result
}


#' @rdname glib-other
#' @title gValueArrayAppend
#'
#' @param value_array ValueArray
#' @param value Value
#' @return ValueArray
#' @export
gValueArrayAppend <- function(value_array, value) {
  .Call("R_g_value_array_append", value_array, value)$result
}


#' @rdname glib-other
#' @title gValueArrayCopy
#'
#' @param value_array ValueArray
#' @return ValueArray
#' @export
gValueArrayCopy <- function(value_array) {
  .Call("R_g_value_array_copy", value_array)$result
}


#' @rdname glib-other
#' @title gValueArrayGetNth
#'
#' @param value_array ValueArray
#' @param index_ guint
#' @return Value
#' @export
gValueArrayGetNth <- function(value_array, index_) {
  .Call("R_g_value_array_get_nth", value_array, as.integer(index_))$result
}


#' @rdname glib-other
#' @title gValueArrayInsert
#'
#' @param value_array ValueArray
#' @param index_ guint
#' @param value Value
#' @return ValueArray
#' @export
gValueArrayInsert <- function(value_array, index_, value) {
  .Call("R_g_value_array_insert", value_array, as.integer(index_), value)$result
}


#' @rdname glib-other
#' @title gValueArrayPrepend
#'
#' @param value_array ValueArray
#' @param value Value
#' @return ValueArray
#' @export
gValueArrayPrepend <- function(value_array, value) {
  .Call("R_g_value_array_prepend", value_array, value)$result
}


#' @rdname glib-other
#' @title gValueArrayRemove
#'
#' @param value_array ValueArray
#' @param index_ guint
#' @return ValueArray
#' @export
gValueArrayRemove <- function(value_array, index_) {
  .Call("R_g_value_array_remove", value_array, as.integer(index_))$result
}


#' @rdname glib-other
#' @title gValueArraySort
#'
#' @param value_array ValueArray
#' @param compare_func function — GLib.CompareFunc function(a, b)
#' @return ValueArray
#' @export
gValueArraySort <- function(value_array, compare_func) {
  .Call("R_g_value_array_sort", value_array, compare_func)$result
}


#' @rdname glib-other
#' @title gValueArraySortWithData
#'
#' @param value_array ValueArray
#' @param compare_func function — GLib.CompareDataFunc function(a, b)
#' @return ValueArray
#' @export
gValueArraySortWithData <- function(value_array, compare_func) {
  .Call("R_g_value_array_sort_with_data", value_array, compare_func)$result
}


#' @rdname glib-other
#' @title gBoxedCopy
#'
#' @param boxed_type GType
#' @param src_boxed gpointer
#' @return gpointer
#' @export
gBoxedCopy <- function(boxed_type, src_boxed) {
  .Call("R_g_boxed_copy", boxed_type, src_boxed)$result
}


#' @rdname glib-other
#' @title gBoxedFree
#'
#' @param boxed_type GType
#' @param boxed gpointer
#' @return Return value from C function
#' @export
gBoxedFree <- function(boxed_type, boxed) {
  invisible(.Call("R_g_boxed_free", boxed_type, boxed))
}


#' @rdname glib-other
#' @title gBoxedTypeRegisterStatic
#'
#' @param name utf8
#' @param boxed_copy function — BoxedCopyFunc function(boxed)
#' @param boxed_free function — BoxedFreeFunc function(boxed)
#' @return GType
#' @export
gBoxedTypeRegisterStatic <- function(name, boxed_copy, boxed_free) {
  .Call("R_g_boxed_type_register_static", name, boxed_copy, boxed_free)$result
}


#' @rdname glib-other
#' @title gEnumCompleteTypeInfo
#'
#' @param g_enum_type GType
#' @param const_values EnumValue
#' @return Return value from C function
#' @export
gEnumCompleteTypeInfo <- function(g_enum_type, const_values) {
  .Call("R_g_enum_complete_type_info", g_enum_type, const_values)$info
}


#' @rdname glib-other
#' @title gEnumGetValue
#'
#' @param enum_class EnumClass
#' @param value gint
#' @return EnumValue
#' @export
gEnumGetValue <- function(enum_class, value) {
  .Call("R_g_enum_get_value", enum_class, as.integer(value))$result
}


#' @rdname glib-other
#' @title gEnumGetValueByName
#'
#' @param enum_class EnumClass
#' @param name utf8
#' @return EnumValue
#' @export
gEnumGetValueByName <- function(enum_class, name) {
  .Call("R_g_enum_get_value_by_name", enum_class, name)$result
}


#' @rdname glib-other
#' @title gEnumGetValueByNick
#'
#' @param enum_class EnumClass
#' @param nick utf8
#' @return EnumValue
#' @export
gEnumGetValueByNick <- function(enum_class, nick) {
  .Call("R_g_enum_get_value_by_nick", enum_class, nick)$result
}


#' @rdname glib-other
#' @title gEnumRegisterStatic
#'
#' @param name utf8
#' @param const_static_values EnumValue
#' @return GType
#' @export
gEnumRegisterStatic <- function(name, const_static_values) {
  .Call("R_g_enum_register_static", name, const_static_values)$result
}


#' @rdname glib-other
#' @title gEnumToString
#'
#' @param g_enum_type GType
#' @param value gint
#' @return utf8
#' @export
gEnumToString <- function(g_enum_type, value) {
  .Call("R_g_enum_to_string", g_enum_type, as.integer(value))$result
}


#' @rdname glib-other
#' @title gFlagsCompleteTypeInfo
#'
#' @param g_flags_type GType
#' @param const_values FlagsValue
#' @return Return value from C function
#' @export
gFlagsCompleteTypeInfo <- function(g_flags_type, const_values) {
  .Call("R_g_flags_complete_type_info", g_flags_type, const_values)$info
}


#' @rdname glib-other
#' @title gFlagsGetFirstValue
#'
#' @param flags_class FlagsClass
#' @param value guint
#' @return FlagsValue
#' @export
gFlagsGetFirstValue <- function(flags_class, value) {
  .Call("R_g_flags_get_first_value", flags_class, as.integer(value))$result
}


#' @rdname glib-other
#' @title gFlagsGetValueByName
#'
#' @param flags_class FlagsClass
#' @param name utf8
#' @return FlagsValue
#' @export
gFlagsGetValueByName <- function(flags_class, name) {
  .Call("R_g_flags_get_value_by_name", flags_class, name)$result
}


#' @rdname glib-other
#' @title gFlagsGetValueByNick
#'
#' @param flags_class FlagsClass
#' @param nick utf8
#' @return FlagsValue
#' @export
gFlagsGetValueByNick <- function(flags_class, nick) {
  .Call("R_g_flags_get_value_by_nick", flags_class, nick)$result
}


#' @rdname glib-other
#' @title gFlagsRegisterStatic
#'
#' @param name utf8
#' @param const_static_values FlagsValue
#' @return GType
#' @export
gFlagsRegisterStatic <- function(name, const_static_values) {
  .Call("R_g_flags_register_static", name, const_static_values)$result
}


#' @rdname glib-other
#' @title gFlagsToString
#'
#' @param flags_type GType
#' @param value guint
#' @return utf8
#' @export
gFlagsToString <- function(flags_type, value) {
  .Call("R_g_flags_to_string", flags_type, as.integer(value))$result
}


#' @rdname glib-other
#' @title gGtypeGetType
#'
#' @return GType
#' @export
gGtypeGetType <- function() {
  .Call("R_g_gtype_get_type")$result
}


#' @rdname glib-other
#' @title gParamSpecBoolean
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param default_value gboolean
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecBoolean <- function(name, nick, blurb, default_value, flags) {
  .Call("R_g_param_spec_boolean", name, nick, blurb, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecBoxed
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param boxed_type GType
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecBoxed <- function(name, nick, blurb, boxed_type, flags) {
  .Call("R_g_param_spec_boxed", name, nick, blurb, boxed_type, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecChar
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum gint8
#' @param maximum gint8
#' @param default_value gint8
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecChar <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_char", name, nick, blurb, as.integer(minimum), as.integer(maximum), as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecDouble
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum gdouble
#' @param maximum gdouble
#' @param default_value gdouble
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecDouble <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_double", name, nick, blurb, minimum, maximum, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecEnum
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param enum_type GType
#' @param default_value gint
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecEnum <- function(name, nick, blurb, enum_type, default_value, flags) {
  .Call("R_g_param_spec_enum", name, nick, blurb, enum_type, as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecFlags
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param flags_type GType
#' @param default_value guint
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecFlags <- function(name, nick, blurb, flags_type, default_value, flags) {
  .Call("R_g_param_spec_flags", name, nick, blurb, flags_type, as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecFloat
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum gfloat
#' @param maximum gfloat
#' @param default_value gfloat
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecFloat <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_float", name, nick, blurb, minimum, maximum, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecGtype
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param is_a_type GType
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecGtype <- function(name, nick, blurb, is_a_type, flags) {
  .Call("R_g_param_spec_gtype", name, nick, blurb, is_a_type, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecInt
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum gint
#' @param maximum gint
#' @param default_value gint
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecInt <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_int", name, nick, blurb, as.integer(minimum), as.integer(maximum), as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecInt64
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum gint64
#' @param maximum gint64
#' @param default_value gint64
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecInt64 <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_int64", name, nick, blurb, minimum, maximum, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecLong
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum glong
#' @param maximum glong
#' @param default_value glong
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecLong <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_long", name, nick, blurb, minimum, maximum, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecObject
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param object_type GType
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecObject <- function(name, nick, blurb, object_type, flags) {
  .Call("R_g_param_spec_object", name, nick, blurb, object_type, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecParam
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param param_type GType
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecParam <- function(name, nick, blurb, param_type, flags) {
  .Call("R_g_param_spec_param", name, nick, blurb, param_type, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecPointer
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecPointer <- function(name, nick, blurb, flags) {
  .Call("R_g_param_spec_pointer", name, nick, blurb, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecString
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param default_value utf8
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecString <- function(name, nick, blurb, default_value, flags) {
  .Call("R_g_param_spec_string", name, nick, blurb, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecUchar
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum guint8
#' @param maximum guint8
#' @param default_value guint8
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecUchar <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_uchar", name, nick, blurb, as.integer(minimum), as.integer(maximum), as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecUint
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum guint
#' @param maximum guint
#' @param default_value guint
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecUint <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_uint", name, nick, blurb, as.integer(minimum), as.integer(maximum), as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecUint64
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum guint64
#' @param maximum guint64
#' @param default_value guint64
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecUint64 <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_uint64", name, nick, blurb, as.integer(minimum), as.integer(maximum), as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecUlong
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param minimum gulong
#' @param maximum gulong
#' @param default_value gulong
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecUlong <- function(name, nick, blurb, minimum, maximum, default_value, flags) {
  .Call("R_g_param_spec_ulong", name, nick, blurb, as.integer(minimum), as.integer(maximum), as.integer(default_value), flags)$result
}


#' @rdname glib-other
#' @title gParamSpecUnichar
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param default_value gunichar
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecUnichar <- function(name, nick, blurb, default_value, flags) {
  .Call("R_g_param_spec_unichar", name, nick, blurb, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamSpecVariant
#'
#' @param name utf8
#' @param nick utf8
#' @param blurb utf8
#' @param type GLib.VariantType
#' @param default_value GLib.Variant
#' @param flags ParamFlags
#' @return ParamSpec
#' @export
gParamSpecVariant <- function(name, nick, blurb, type, default_value, flags) {
  .Call("R_g_param_spec_variant", name, nick, blurb, type, default_value, flags)$result
}


#' @rdname glib-other
#' @title gParamTypeRegisterStatic
#'
#' @param name utf8
#' @param pspec_info ParamSpecTypeInfo
#' @return GType
#' @export
gParamTypeRegisterStatic <- function(name, pspec_info) {
  .Call("R_g_param_type_register_static", name, pspec_info)$result
}


#' @rdname glib-other
#' @title gParamValueConvert
#'
#' @param pspec ParamSpec
#' @param src_value Value
#' @param dest_value Value
#' @param strict_validation gboolean
#' @return gboolean
#' @export
gParamValueConvert <- function(pspec, src_value, dest_value, strict_validation) {
  .Call("R_g_param_value_convert", pspec, src_value, dest_value, strict_validation)$result
}


#' @rdname glib-other
#' @title gParamValueDefaults
#'
#' @param pspec ParamSpec
#' @param value Value
#' @return gboolean
#' @export
gParamValueDefaults <- function(pspec, value) {
  .Call("R_g_param_value_defaults", pspec, value)$result
}


#' @rdname glib-other
#' @title gParamValueSetDefault
#'
#' @param pspec ParamSpec
#' @param value Value
#' @return Return value from C function
#' @export
gParamValueSetDefault <- function(pspec, value) {
  invisible(.Call("R_g_param_value_set_default", pspec, value))
}


#' @rdname glib-other
#' @title gParamValueValidate
#'
#' @param pspec ParamSpec
#' @param value Value
#' @return gboolean
#' @export
gParamValueValidate <- function(pspec, value) {
  .Call("R_g_param_value_validate", pspec, value)$result
}


#' @rdname glib-other
#' @title gParamValuesCmp
#'
#' @param pspec ParamSpec
#' @param value1 Value
#' @param value2 Value
#' @return gint
#' @export
gParamValuesCmp <- function(pspec, value1, value2) {
  .Call("R_g_param_values_cmp", pspec, value1, value2)$result
}


#' @rdname glib-other
#' @title gPointerTypeRegisterStatic
#'
#' @param name utf8
#' @return GType
#' @export
gPointerTypeRegisterStatic <- function(name) {
  .Call("R_g_pointer_type_register_static", name)$result
}


#' @rdname gobject-core
#' @title gSignalAccumulatorFirstWins
#'
#' @param ihint SignalInvocationHint
#' @param return_accu Value
#' @param handler_return Value
#' @param dummy gpointer
#' @return gboolean
#' @export
gSignalAccumulatorFirstWins <- function(ihint, return_accu, handler_return, dummy) {
  .Call("R_g_signal_accumulator_first_wins", ihint, return_accu, handler_return, dummy)$result
}


#' @rdname gobject-core
#' @title gSignalAccumulatorTrueHandled
#'
#' @param ihint SignalInvocationHint
#' @param return_accu Value
#' @param handler_return Value
#' @param dummy gpointer
#' @return gboolean
#' @export
gSignalAccumulatorTrueHandled <- function(ihint, return_accu, handler_return, dummy) {
  .Call("R_g_signal_accumulator_true_handled", ihint, return_accu, handler_return, dummy)$result
}


#' @rdname gobject-core
#' @title gSignalAddEmissionHook
#'
#' @param signal_id guint
#' @param detail GLib.Quark
#' @param hook_func function — SignalEmissionHook function(ihint, n_param_values, param_values)
#' @return gulong
#' @export
gSignalAddEmissionHook <- function(signal_id, detail, hook_func) {
  .Call("R_g_signal_add_emission_hook", as.integer(signal_id), detail, hook_func)$result
}


#' @rdname gobject-core
#' @title gSignalChainFromOverridden
#'
#' @param instance_and_params Value
#' @param return_value Value
#' @return Return value from C function
#' @export
gSignalChainFromOverridden <- function(instance_and_params, return_value) {
  invisible(.Call("R_g_signal_chain_from_overridden", instance_and_params, return_value))
}


#' @rdname gobject-core
#' @title gSignalConnectClosure
#'
#' @param instance Object
#' @param detailed_signal utf8
#' @param closure Closure
#' @param after gboolean
#' @return gulong
#' @export
gSignalConnectClosure <- function(instance, detailed_signal, closure, after) {
  .Call("R_g_signal_connect_closure", instance, detailed_signal, closure, after)$result
}


#' @rdname gobject-core
#' @title gSignalConnectClosureById
#'
#' @param instance Object
#' @param signal_id guint
#' @param detail GLib.Quark
#' @param closure Closure
#' @param after gboolean
#' @return gulong
#' @export
gSignalConnectClosureById <- function(instance, signal_id, detail, closure, after) {
  .Call("R_g_signal_connect_closure_by_id", instance, as.integer(signal_id), detail, closure, after)$result
}


#' @rdname gobject-core
#' @title gSignalEmitv
#'
#' @param instance_and_params Value
#' @param signal_id guint
#' @param detail GLib.Quark
#' @return Return value from C function
#' @export
gSignalEmitv <- function(instance_and_params, signal_id, detail) {
  .Call("R_g_signal_emitv", instance_and_params, as.integer(signal_id), detail)$return_value
}


#' @rdname gobject-core
#' @title gSignalGetInvocationHint
#'
#' @param instance Object
#' @return SignalInvocationHint
#' @export
gSignalGetInvocationHint <- function(instance) {
  .Call("R_g_signal_get_invocation_hint", instance)$result
}


#' @rdname gobject-core
#' @title gSignalHandlerBlock
#'
#' @param instance Object
#' @param handler_id gulong
#' @return Return value from C function
#' @export
gSignalHandlerBlock <- function(instance, handler_id) {
  invisible(.Call("R_g_signal_handler_block", instance, as.integer(handler_id)))
}


#' @rdname gobject-core
#' @title gSignalHandlerDisconnect
#'
#' @param instance Object
#' @param handler_id gulong
#' @return Return value from C function
#' @export
gSignalHandlerDisconnect <- function(instance, handler_id) {
  invisible(.Call("R_g_signal_handler_disconnect", instance, as.integer(handler_id)))
}


#' @rdname gobject-core
#' @title gSignalHandlerFind
#'
#' @param instance Object
#' @param mask SignalMatchType
#' @param signal_id guint
#' @param detail GLib.Quark
#' @param closure Closure
#' @param func gpointer
#' @param data gpointer
#' @return gulong
#' @export
gSignalHandlerFind <- function(instance, mask, signal_id, detail, closure, func, data) {
  .Call("R_g_signal_handler_find", instance, mask, as.integer(signal_id), detail, closure, func, data)$result
}


#' @rdname gobject-core
#' @title gSignalHandlerIsConnected
#'
#' @param instance Object
#' @param handler_id gulong
#' @return gboolean
#' @export
gSignalHandlerIsConnected <- function(instance, handler_id) {
  .Call("R_g_signal_handler_is_connected", instance, as.integer(handler_id))$result
}


#' @rdname gobject-core
#' @title gSignalHandlerUnblock
#'
#' @param instance Object
#' @param handler_id gulong
#' @return Return value from C function
#' @export
gSignalHandlerUnblock <- function(instance, handler_id) {
  invisible(.Call("R_g_signal_handler_unblock", instance, as.integer(handler_id)))
}


#' @rdname gobject-core
#' @title gSignalHandlersBlockMatched
#'
#' @param instance Object
#' @param mask SignalMatchType
#' @param signal_id guint
#' @param detail GLib.Quark
#' @param closure Closure
#' @param func gpointer
#' @param data gpointer
#' @return guint
#' @export
gSignalHandlersBlockMatched <- function(instance, mask, signal_id, detail, closure, func, data) {
  .Call("R_g_signal_handlers_block_matched", instance, mask, as.integer(signal_id), detail, closure, func, data)$result
}


#' @rdname gobject-core
#' @title gSignalHandlersDestroy
#'
#' @param instance Object
#' @return Return value from C function
#' @export
gSignalHandlersDestroy <- function(instance) {
  invisible(.Call("R_g_signal_handlers_destroy", instance))
}


#' @rdname gobject-core
#' @title gSignalHandlersDisconnectMatched
#'
#' @param instance Object
#' @param mask SignalMatchType
#' @param signal_id guint
#' @param detail GLib.Quark
#' @param closure Closure
#' @param func gpointer
#' @param data gpointer
#' @return guint
#' @export
gSignalHandlersDisconnectMatched <- function(instance, mask, signal_id, detail, closure, func, data) {
  .Call("R_g_signal_handlers_disconnect_matched", instance, mask, as.integer(signal_id), detail, closure, func, data)$result
}


#' @rdname gobject-core
#' @title gSignalHandlersUnblockMatched
#'
#' @param instance Object
#' @param mask SignalMatchType
#' @param signal_id guint
#' @param detail GLib.Quark
#' @param closure Closure
#' @param func gpointer
#' @param data gpointer
#' @return guint
#' @export
gSignalHandlersUnblockMatched <- function(instance, mask, signal_id, detail, closure, func, data) {
  .Call("R_g_signal_handlers_unblock_matched", instance, mask, as.integer(signal_id), detail, closure, func, data)$result
}


#' @rdname gobject-core
#' @title gSignalHasHandlerPending
#'
#' @param instance Object
#' @param signal_id guint
#' @param detail GLib.Quark
#' @param may_be_blocked gboolean
#' @return gboolean
#' @export
gSignalHasHandlerPending <- function(instance, signal_id, detail, may_be_blocked) {
  .Call("R_g_signal_has_handler_pending", instance, as.integer(signal_id), detail, may_be_blocked)$result
}


#' @rdname gobject-core
#' @title gSignalListIds
#'
#' @param itype GType
#' @return guint
#' @export
gSignalListIds <- function(itype) {
  .Call("R_g_signal_list_ids", itype)
}


#' @rdname gobject-core
#' @title gSignalLookup
#'
#' @param name utf8
#' @param itype GType
#' @return guint
#' @export
gSignalLookup <- function(name, itype) {
  .Call("R_g_signal_lookup", name, itype)$result
}


#' @rdname gobject-core
#' @title gSignalName
#'
#' @param signal_id guint
#' @return utf8
#' @export
gSignalName <- function(signal_id) {
  .Call("R_g_signal_name", as.integer(signal_id))$result
}


#' @rdname gobject-core
#' @title gSignalOverrideClassClosure
#'
#' @param signal_id guint
#' @param instance_type GType
#' @param class_closure Closure
#' @return Return value from C function
#' @export
gSignalOverrideClassClosure <- function(signal_id, instance_type, class_closure) {
  invisible(.Call("R_g_signal_override_class_closure", as.integer(signal_id), instance_type, class_closure))
}


#' @rdname gobject-core
#' @title gSignalOverrideClassHandler
#'
#' @param signal_name utf8
#' @param instance_type GType
#' @param class_handler function — Callback function()
#' @return Return value from C function
#' @export
gSignalOverrideClassHandler <- function(signal_name, instance_type, class_handler) {
  invisible(.Call("R_g_signal_override_class_handler", signal_name, instance_type, class_handler))
}


#' @rdname gobject-core
#' @title gSignalParseName
#'
#' @param detailed_signal utf8
#' @param itype GType
#' @param force_detail_quark gboolean
#' @return gboolean
#' @export
gSignalParseName <- function(detailed_signal, itype, force_detail_quark) {
  .Call("R_g_signal_parse_name", detailed_signal, itype, force_detail_quark)
}


#' @rdname gobject-core
#' @title gSignalQuery
#'
#' @param signal_id guint
#' @return Return value from C function
#' @export
gSignalQuery <- function(signal_id) {
  .Call("R_g_signal_query", as.integer(signal_id))$query
}


#' @rdname gobject-core
#' @title gSignalRemoveEmissionHook
#'
#' @param signal_id guint
#' @param hook_id gulong
#' @return Return value from C function
#' @export
gSignalRemoveEmissionHook <- function(signal_id, hook_id) {
  invisible(.Call("R_g_signal_remove_emission_hook", as.integer(signal_id), as.integer(hook_id)))
}


#' @rdname gobject-core
#' @title gSignalStopEmission
#'
#' @param instance Object
#' @param signal_id guint
#' @param detail GLib.Quark
#' @return Return value from C function
#' @export
gSignalStopEmission <- function(instance, signal_id, detail) {
  invisible(.Call("R_g_signal_stop_emission", instance, as.integer(signal_id), detail))
}


#' @rdname gobject-core
#' @title gSignalStopEmissionByName
#'
#' @param instance Object
#' @param detailed_signal utf8
#' @return Return value from C function
#' @export
gSignalStopEmissionByName <- function(instance, detailed_signal) {
  invisible(.Call("R_g_signal_stop_emission_by_name", instance, detailed_signal))
}


#' @rdname gobject-core
#' @title gSignalTypeCclosureNew
#'
#' @param itype GType
#' @param struct_offset guint
#' @return Closure
#' @export
gSignalTypeCclosureNew <- function(itype, struct_offset) {
  .Call("R_g_signal_type_cclosure_new", itype, as.integer(struct_offset))$result
}


#' @rdname glib-strings
#' @title gStrdupValueContents
#'
#' @param value Value
#' @return utf8
#' @export
gStrdupValueContents <- function(value) {
  .Call("R_g_strdup_value_contents", value)$result
}


#' @rdname glib-other
#' @title gTypeAddClassPrivate
#'
#' @param class_type GType
#' @param private_size gsize
#' @return Return value from C function
#' @export
gTypeAddClassPrivate <- function(class_type, private_size) {
  invisible(.Call("R_g_type_add_class_private", class_type, as.integer(private_size)))
}


#' @rdname glib-other
#' @title gTypeAddInstancePrivate
#'
#' @param class_type GType
#' @param private_size gsize
#' @return gint
#' @export
gTypeAddInstancePrivate <- function(class_type, private_size) {
  .Call("R_g_type_add_instance_private", class_type, as.integer(private_size))$result
}


#' @rdname glib-other
#' @title gTypeAddInterfaceDynamic
#'
#' @param instance_type GType
#' @param interface_type GType
#' @param plugin TypePlugin
#' @return Return value from C function
#' @export
gTypeAddInterfaceDynamic <- function(instance_type, interface_type, plugin) {
  invisible(.Call("R_g_type_add_interface_dynamic", instance_type, interface_type, plugin))
}


#' @rdname glib-other
#' @title gTypeAddInterfaceStatic
#'
#' @param instance_type GType
#' @param interface_type GType
#' @param info InterfaceInfo
#' @return Return value from C function
#' @export
gTypeAddInterfaceStatic <- function(instance_type, interface_type, info) {
  invisible(.Call("R_g_type_add_interface_static", instance_type, interface_type, info))
}


#' @rdname glib-other
#' @title gTypeCheckClassIsA
#'
#' @param g_class TypeClass
#' @param is_a_type GType
#' @return gboolean
#' @export
gTypeCheckClassIsA <- function(g_class, is_a_type) {
  .Call("R_g_type_check_class_is_a", g_class, is_a_type)$result
}


#' @rdname glib-other
#' @title gTypeCheckInstance
#'
#' @param instance TypeInstance
#' @return gboolean
#' @export
gTypeCheckInstance <- function(instance) {
  .Call("R_g_type_check_instance", instance)$result
}


#' @rdname glib-other
#' @title gTypeCheckInstanceIsA
#'
#' @param instance TypeInstance
#' @param iface_type GType
#' @return gboolean
#' @export
gTypeCheckInstanceIsA <- function(instance, iface_type) {
  .Call("R_g_type_check_instance_is_a", instance, iface_type)$result
}


#' @rdname glib-other
#' @title gTypeCheckInstanceIsFundamentallyA
#'
#' @param instance TypeInstance
#' @param fundamental_type GType
#' @return gboolean
#' @export
gTypeCheckInstanceIsFundamentallyA <- function(instance, fundamental_type) {
  .Call("R_g_type_check_instance_is_fundamentally_a", instance, fundamental_type)$result
}


#' @rdname glib-other
#' @title gTypeCheckIsValueType
#'
#' @param type GType
#' @return gboolean
#' @export
gTypeCheckIsValueType <- function(type) {
  .Call("R_g_type_check_is_value_type", type)$result
}


#' @rdname glib-other
#' @title gTypeCheckValue
#'
#' @param value Value
#' @return gboolean
#' @export
gTypeCheckValue <- function(value) {
  .Call("R_g_type_check_value", value)$result
}


#' @rdname glib-other
#' @title gTypeCheckValueHolds
#'
#' @param value Value
#' @param type GType
#' @return gboolean
#' @export
gTypeCheckValueHolds <- function(value, type) {
  .Call("R_g_type_check_value_holds", value, type)$result
}


#' @rdname glib-other
#' @title gTypeChildren
#'
#' @param type GType
#' @return GType
#' @export
gTypeChildren <- function(type) {
  .Call("R_g_type_children", type)
}


#' @rdname glib-other
#' @title gTypeDefaultInterfacePeek
#'
#' @param g_type GType
#' @return TypeInterface
#' @export
gTypeDefaultInterfacePeek <- function(g_type) {
  .Call("R_g_type_default_interface_peek", g_type)$result
}


#' @rdname glib-other
#' @title gTypeDefaultInterfaceRef
#'
#' @param g_type GType
#' @return TypeInterface
#' @export
gTypeDefaultInterfaceRef <- function(g_type) {
  .Call("R_g_type_default_interface_ref", g_type)$result
}


#' @rdname glib-other
#' @title gTypeDefaultInterfaceUnref
#'
#' @param g_iface TypeInterface
#' @return Return value from C function
#' @export
gTypeDefaultInterfaceUnref <- function(g_iface) {
  invisible(.Call("R_g_type_default_interface_unref", g_iface))
}


#' @rdname glib-other
#' @title gTypeDepth
#'
#' @param type GType
#' @return guint
#' @export
gTypeDepth <- function(type) {
  .Call("R_g_type_depth", type)$result
}


#' @rdname glib-other
#' @title gTypeEnsure
#'
#' @param type GType
#' @return Return value from C function
#' @export
gTypeEnsure <- function(type) {
  invisible(.Call("R_g_type_ensure", type))
}


#' @rdname glib-other
#' @title gTypeFreeInstance
#'
#' @param instance TypeInstance
#' @return Return value from C function
#' @export
gTypeFreeInstance <- function(instance) {
  invisible(.Call("R_g_type_free_instance", instance))
}


#' @rdname glib-other
#' @title gTypeFromName
#'
#' @param name utf8
#' @return GType
#' @export
gTypeFromName <- function(name) {
  .Call("R_g_type_from_name", name)$result
}


#' @rdname glib-other
#' @title gTypeFundamental
#'
#' @param type_id GType
#' @return GType
#' @export
gTypeFundamental <- function(type_id) {
  .Call("R_g_type_fundamental", type_id)$result
}


#' @rdname glib-other
#' @title gTypeFundamentalNext
#'
#' @return GType
#' @export
gTypeFundamentalNext <- function() {
  .Call("R_g_type_fundamental_next")$result
}


#' @rdname glib-other
#' @title gTypeGetInstanceCount
#'
#' @param type GType
#' @return gint
#' @export
gTypeGetInstanceCount <- function(type) {
  .Call("R_g_type_get_instance_count", type)$result
}


#' @rdname glib-other
#' @title gTypeGetPlugin
#'
#' @param type GType
#' @return TypePlugin
#' @export
gTypeGetPlugin <- function(type) {
  .Call("R_g_type_get_plugin", type)$result
}


#' @rdname glib-other
#' @title gTypeGetQdata
#'
#' @param type GType
#' @param quark GLib.Quark
#' @return gpointer
#' @export
gTypeGetQdata <- function(type, quark) {
  .Call("R_g_type_get_qdata", type, quark)$result
}


#' @rdname glib-other
#' @title gTypeGetTypeRegistrationSerial
#'
#' @return guint
#' @export
gTypeGetTypeRegistrationSerial <- function() {
  .Call("R_g_type_get_type_registration_serial")$result
}


#' @rdname glib-other
#' @title gTypeInit
#'
#' @return Return value from C function
#' @export
gTypeInit <- function() {
  invisible(.Call("R_g_type_init"))
}


#' @rdname glib-other
#' @title gTypeInitWithDebugFlags
#'
#' @param debug_flags TypeDebugFlags
#' @return Return value from C function
#' @export
gTypeInitWithDebugFlags <- function(debug_flags) {
  invisible(.Call("R_g_type_init_with_debug_flags", debug_flags))
}


#' @rdname glib-other
#' @title gTypeInterfaces
#'
#' @param type GType
#' @return GType
#' @export
gTypeInterfaces <- function(type) {
  .Call("R_g_type_interfaces", type)
}


#' @rdname glib-other
#' @title gTypeIsA
#'
#' @param type GType
#' @param is_a_type GType
#' @return gboolean
#' @export
gTypeIsA <- function(type, is_a_type) {
  .Call("R_g_type_is_a", type, is_a_type)$result
}


#' @rdname glib-other
#' @title gTypeName
#'
#' @param type GType
#' @return utf8
#' @export
gTypeName <- function(type) {
  .Call("R_g_type_name", type)$result
}


#' @rdname glib-other
#' @title gTypeNameFromClass
#'
#' @param g_class TypeClass
#' @return utf8
#' @export
gTypeNameFromClass <- function(g_class) {
  .Call("R_g_type_name_from_class", g_class)$result
}


#' @rdname glib-other
#' @title gTypeNameFromInstance
#'
#' @param instance TypeInstance
#' @return utf8
#' @export
gTypeNameFromInstance <- function(instance) {
  .Call("R_g_type_name_from_instance", instance)$result
}


#' @rdname glib-other
#' @title gTypeNextBase
#'
#' @param leaf_type GType
#' @param root_type GType
#' @return GType
#' @export
gTypeNextBase <- function(leaf_type, root_type) {
  .Call("R_g_type_next_base", leaf_type, root_type)$result
}


#' @rdname glib-other
#' @title gTypeParent
#'
#' @param type GType
#' @return GType
#' @export
gTypeParent <- function(type) {
  .Call("R_g_type_parent", type)$result
}


#' @rdname glib-other
#' @title gTypeQname
#'
#' @param type GType
#' @return GLib.Quark
#' @export
gTypeQname <- function(type) {
  .Call("R_g_type_qname", type)$result
}


#' @rdname glib-other
#' @title gTypeQuery
#'
#' @param type GType
#' @return Return value from C function
#' @export
gTypeQuery <- function(type) {
  .Call("R_g_type_query", type)$query
}


#' @rdname glib-other
#' @title gTypeRegisterDynamic
#'
#' @param parent_type GType
#' @param type_name utf8
#' @param plugin TypePlugin
#' @param flags TypeFlags
#' @return GType
#' @export
gTypeRegisterDynamic <- function(parent_type, type_name, plugin, flags) {
  .Call("R_g_type_register_dynamic", parent_type, type_name, plugin, flags)$result
}


#' @rdname glib-other
#' @title gTypeRegisterFundamental
#'
#' @param type_id GType
#' @param type_name utf8
#' @param info TypeInfo
#' @param finfo TypeFundamentalInfo
#' @param flags TypeFlags
#' @return GType
#' @export
gTypeRegisterFundamental <- function(type_id, type_name, info, finfo, flags) {
  .Call("R_g_type_register_fundamental", type_id, type_name, info, finfo, flags)$result
}


#' @rdname glib-other
#' @title gTypeRegisterStatic
#'
#' @param parent_type GType
#' @param type_name utf8
#' @param info TypeInfo
#' @param flags TypeFlags
#' @return GType
#' @export
gTypeRegisterStatic <- function(parent_type, type_name, info, flags) {
  .Call("R_g_type_register_static", parent_type, type_name, info, flags)$result
}


#' @rdname glib-other
#' @title gTypeSetQdata
#'
#' @param type GType
#' @param quark GLib.Quark
#' @param data gpointer
#' @return Return value from C function
#' @export
gTypeSetQdata <- function(type, quark, data) {
  invisible(.Call("R_g_type_set_qdata", type, quark, data))
}


#' @rdname glib-other
#' @title gTypeTestFlags
#'
#' @param type GType
#' @param flags guint
#' @return gboolean
#' @export
gTypeTestFlags <- function(type, flags) {
  .Call("R_g_type_test_flags", type, as.integer(flags))$result
}


# Enumerations

# BindingFlags
DEFAULT <- 0
BIDIRECTIONAL <- 1
SYNC_CREATE <- 2
INVERT_BOOLEAN <- 4

# ConnectFlags
DEFAULT <- 0
AFTER <- 1
SWAPPED <- 2

# IOCondition
IN <- 1
OUT <- 4
PRI <- 2
ERR <- 8
HUP <- 16
NVAL <- 32

# ParamFlags
READABLE <- 1
WRITABLE <- 2
READWRITE <- 3
CONSTRUCT <- 4
CONSTRUCT_ONLY <- 8
LAX_VALIDATION <- 16
STATIC_NAME <- 32
PRIVATE <- 32
STATIC_NICK <- 64
STATIC_BLURB <- 128
EXPLICIT_NOTIFY <- 1073741824
DEPRECATED <- 2147483648

# SignalFlags
RUN_FIRST <- 1
RUN_LAST <- 2
RUN_CLEANUP <- 4
NO_RECURSE <- 8
DETAILED <- 16
ACTION <- 32
NO_HOOKS <- 64
MUST_COLLECT <- 128
DEPRECATED <- 256
ACCUMULATOR_FIRST_RUN <- 131072

# SignalMatchType
ID <- 1
DETAIL <- 2
CLOSURE <- 4
FUNC <- 8
DATA <- 16
UNBLOCKED <- 32

# TypeDebugFlags
NONE <- 0
OBJECTS <- 1
SIGNALS <- 2
INSTANCE_COUNT <- 4
MASK <- 7

# TypeFlags
NONE <- 0
ABSTRACT <- 16
VALUE_ABSTRACT <- 32
FINAL <- 64
DEPRECATED <- 128

# TypeFundamentalFlags
CLASSED <- 1
INSTANTIATABLE <- 2
DERIVABLE <- 4
DEEP_DERIVABLE <- 8
